### ISSUE TITLE
Error: `labels` not implemented for nested resampling

### ISSUE THREAD

**Issue by gtalckmin** [tidymodels/rsample#119]
Hi,
I am running on the following error:

library(tidymodels)
nested_cv(data = iris, outside = group_vfold_cv( data = iris, group = Species, v = 2), inside = bootstraps(times = 5)) %>% rsample2caret()

>Error: `labels` not implemented for nested resampling

I am unsure it is on development or if there is a correct way to input it trainControl.
Thanks and congratulations

**Comment by juliasilge** [comment]
If you look at `?rsample2caret`, you will notice that the first argument is an `rset` object, but it says:

```
Currently, nested_cv is not supported.
```

Converting these objects to the caret format is not on our roadmap in the near term. If you would like to use nested resampling in modeling, check out [this article on `tidymodels.org`](https://www.tidymodels.org/learn/work/nested-resampling/).
