### ISSUE TITLE
Idea new function inital_split_id

### ISSUE THREAD

**Issue by brunocarlin** [tidymodels/rsample#122]
I think the initial_split function should include a group argument or that there should be a new function that respects the ids of the variables to be sampled, if you guys could allow for more than one grouping variable that would also be great

Demo implementation using group_vfold_cv
``` r
library(tidyverse)
library(tidymodels)

set.seed(3527)
test_data <- data.frame(id = sort(sample(1:20, size = 80, replace = TRUE)))

inital_split_id <- function(data,group,prop = 3/4) {
  count_v <- data %>% 
    pull({{group}}) %>% 
    unique() %>% 
    length() *(1-prop)
  group_vfold_cv(data,{{group}},count_v) %>% 
    head(1) %>%
    pull(1) %>% 
    pluck(1)
}

test_data %>% inital_split_id(group = id,prop = .8)
#> <62/18/80>
```

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brunocarlin** [comment]
Ok I derped on the first implementation

```
inital_split_id <- function(data,group,prop = 3/4) {
  group_vfold_cv(data,{{group}},1/(1-prop)) %>%
    head(1) %>%
    pull(1) %>%
    pluck(1)
}
```

**Comment by juliasilge** [comment]
We believe the best way to create these kind of strata is to explicitly create them yourself as the analyst using domain knowledge, typically using `mutate()` and something like `paste()` or `glue()` if you prefer. For example, you can paste any number of grouping variables together and use that as your strata:

``` r
library(rsample)
#> Loading required package: tidyr
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

mtcars %>%
  mutate(new_strata = paste0(vs, gear, sep = "_")) %>%
  bootstraps(strata = new_strata)
#> # Bootstrap sampling using stratification 
#> # A tibble: 25 x 2
#>    splits          id         
#>    <named list>    <chr>      
#>  1 <split [32/11]> Bootstrap01
#>  2 <split [32/11]> Bootstrap02
#>  3 <split [32/10]> Bootstrap03
#>  4 <split [32/12]> Bootstrap04
#>  5 <split [32/10]> Bootstrap05
#>  6 <split [32/13]> Bootstrap06
#>  7 <split [32/11]> Bootstrap07
#>  8 <split [32/12]> Bootstrap08
#>  9 <split [32/12]> Bootstrap09
#> 10 <split [32/10]> Bootstrap10
#> # … with 15 more rows
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by brunocarlin** [comment]
Hi @juliasilge  While I do agree glue is a very elegant solution to the multiple groups problem, I don't thing there is a function that implements grouped sampling  other than group_vfold_cv, stratas are not what I was trying to solve.

Think of this example we have a dataset with multiple instances of the individual,

If we simply strata by the individual id it doesn't guarantee that the individual will not be on the training and test set at the same time causing a leaking problem.

group_vfold_cv solves the leaking problem but it ins't built with the prop argument in mind, I guess one way to think about this feature request would be something like implementing group_initial_split,

Once again thanks for the excellent package

**Comment by juliasilge** [comment]
Related to #164
