### ISSUE TITLE
Feature request: leave group out cross-validation

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/rsample#129]
To valid, say, random intercepts models, you need to leave entire groups of users out at the same time because they have correlated outcomes. Infrastructure to support cross-validation of basic dependence structures would be really nice.

**Comment by topepo** [comment]
[`group_vfold_cv()`](https://tidymodels.github.io/rsample/reference/group_vfold_cv.html)?

**Comment by alexpghayes** [comment]
Bless.
