### ISSUE TITLE
Bootstrap using rsample package is much slower than using boot package?

### ISSUE THREAD

**Issue by danilinares** [tidymodels/rsample#133]
I found that rsample is much slower than boot. Here, a very simple example:

https://stackoverflow.com/questions/60505342/bootstrap-using-rsample-package-is-much-slower-than-using-boot-package

I am not sure I am using rsample properly.

**Comment by topepo** [comment]
It's the computational price for using `dplyr` verbs and, in some ways, our system being more versatile. 

You should take a look at @DavisVaughan's [`strapgod`](https://github.com/DavisVaughan/strapgod).
