### ISSUE TITLE
summary and analysis code

### ISSUE THREAD

**Issue by topepo** [tidymodels/rsample#14]
- [ ] Basic mean, sd, summary, and other methods for naive summaries of columns that are not splits, id's, or other complex objects. Maybe default it to any numeric columns and make sure to filter out apparent sampling for bootstrapping. Also use `tidyselect` for tidyverse name specifications. 
- [ ] Add more complex methods for these summaries that are bias corrected (such as 632, 632+)
- [ ] Consider an `as.boot` or similar function that allows to go from the tibble output to the ones in other package. 
- [ ] Also considering importing those functions and writing wrappers to do traditional resampling statistics from the tibble.

**Comment by topepo** [comment]
Ug. Basic statistics in R are generic methods without the `...`:
```r
> median
function (x, na.rm = FALSE) 
UseMethod("median")
<bytecode: 0x103ac2600>
<environment: namespace:stats>
```
This would impact how we pick the variables in the tibble to summarize.

**Comment by topepo** [comment]
Instead, write a `summarize` method for `rset` objects and use selectors (via the `...`) to choose which _numeric_ columns to summarize. The summaries should extend `broom::tidy.summaryDefault` to (always) include the number of missing values and the std. deviation. 

Perhaps add a `method` or similar argument so that it can be extended later with more sophisticated metrics (e.g. boot 632) and have the default be "naive" to get the results described above.

**Comment by topepo** [comment]
Maybe also have "estimate" instead of "mean" as the column name. That would allow standardization of names across methods. In that was boot632 will have `NA` for the quantiles and std. dev. columns.

**Comment by topepo** [comment]
Perhaps link a `method = "glm"` to `tidyposterior` to get the credible interval. Perhaps add an `upper`, `lower`, and `prob` argument to the list for the intervals or make a different method (`confint`?) for estimating the intervals.

**Comment by abernauer** [comment]
If this enhancement is still a goal would be up to help with the issue.

**Comment by juliasilge** [comment]
This work is happening in other packages and/or has been superseded so I am closing this older issue! 🙌
