### ISSUE TITLE
Feature request - scientific paper that supports stratified sampling of numeric variables?

### ISSUE THREAD

**Issue by skeller88** [tidymodels/rsample#151]
There is clear evidence for stratification of the dependent variable for classification problems. [Kohavi (1995)](https://www.researchgate.net/publication/2352264_A_Study_of_Cross-Validation_and_Bootstrap_for_Accuracy_Estimation_and_Model_Selection) finds that "stratification is generally a better scheme, both in terms of bias and variance, when compared to regular cross-validation". This is especially true when datasets are imbalanced. [Forman (2010) ](https://www.researchgate.net/publication/220520176_Apples-to-Apples_in_Cross-Validation_Studies_Pitfalls_in_Classifier_Performance_Measurement_ABSTRACT) also recommends stratification and notes that it avoids having zero positives in one or more of the folds, which would lead to undefined recall and undefined AUC.

However, I've been unable to find a scientific paper that clearly provides evidence for stratification of a dependent variable for regression problems. Is anyone aware of such a paper? If not, what's the justification for stratification of continuous variables, other than the fact that there's evidence for discrete variables?

**Comment by topepo** [comment]
Not really (outside of books that I've published). I have anecdotal data sets that show that it would be problematic to do simple sampling when the outcome has a long tail but not peer-reviewed research. 

This has come up a lot on the SKL PR (maybe that brought you here?).

**Comment by skeller88** [comment]
Makes sense and jives with what I've seen in my literature review.

SKL as in "scikit-learn"? If so, yes. The core team wanted some evidence
for the new binned (stratified) regression cv feature, and I was trying to
find some. The best I could find was a R ML guide by Boehmke & Greenwell
(2020) <https://bradleyboehmke.github.io/HOML/process.html>. If you want to
chime in on the SKL issue
<https://github.com/scikit-learn/scikit-learn/pull/14560>, please do as I
think that would help the team make the final decision to move forward with
the PR.

**Comment by topepo** [comment]
I've [commented already](https://github.com/scikit-learn/scikit-learn/pull/14560#issuecomment-535204456) saying the same thing as above.

**Comment by skeller88** [comment]
Got it. Thanks.
