### ISSUE TITLE
rsample::group_vfold_cv -> splits . Factors converted to characters

### ISSUE THREAD

**Issue by gtalckmin** [tidymodels/rsample#167]
Hello,
I noticed that the newest version of rsample is transforming variables from factors to characters (within the splits at least), when applying group_vfold_cv.

In turn, if one is keen to use a formula (at least for the pls package):
`plsr(y~ -factor,...) `
the predict function outputs this error:
`Error in `contrasts<-`(`tmp`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels `

**Comment by topepo** [comment]
Can you provide a small, reproducible example?
