### ISSUE TITLE
dplyr rowwise.rset method

### ISSUE THREAD

**Issue by sccmckenzie** [tidymodels/rsample#174]
Hello, I noticed that `dplyr::rowwise()` strips `rset` class.

Though using `purrr::map()` is more succinct in this example, in principle it would be nice to leverage `rowwise()` functionality with `rsample`. Is it possible to create a `rowwise.rset` method?

``` r
library(rsample)
library(broom)
library(purrr)
library(dplyr)

boots <- bootstraps(mtcars, times = 20, apparent = TRUE)
```

### Method 1: purrr
Expected output (normal)
``` r
boots %>% 
  mutate(model = map(splits, ~ lm(mpg ~ disp, data = analysis(..1))),
         coef_info = map(model, tidy)) %>% 
  int_pctl(coef_info)

#> Warning: Recommend at least 1000 non-missing bootstrap resamples for terms:
#> `(Intercept)`, `disp`.
#> # A tibble: 2 x 6
#>   term         .lower .estimate  .upper .alpha .method   
#>   <chr>         <dbl>     <dbl>   <dbl>  <dbl> <chr>     
#> 1 (Intercept) 26.9      29.9    32.6      0.05 percentile
#> 2 disp        -0.0521   -0.0428 -0.0328   0.05 percentile
```

### Method 2: rowwise()
rset class is stripped
```r
boots %>% 
  rowwise() %>% 
  mutate(mod = list(nls(mpg ~ k / wt + b, analysis(splits), start = list(k = 1, b = 0))),
         coef_info = list(tidy(mod))) %>% 
  ungroup() %>%
  int_pctl(coef_info)

#> Error: `.data` should be an `rset` object generated from `bootstraps()`
```

<sup>Created on 2020-08-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by topepo** [comment]
Hmm. Maybe. `vctrs` required formal definitions of how row- and column- operations affect the resulting class. I'll punt this to @DavisVaughan

**Comment by DavisVaughan** [comment]
I don't think that dplyr is really set up for this kind of support. It is sort of like making a grouped_df subclass, which is also an uphill battle. We also lose the class when a `group_by()` is called. I think losing the class when `group_by()` and `rowwise()` are called is expected behavior for now.

```r
> dplyr::group_by(bootstraps(mtcars), id)
# A tibble: 25 x 2
# Groups:   id [25]
   splits          id         
   <list>          <chr>      
 1 <split [32/11]> Bootstrap01
 2 <split [32/14]> Bootstrap02
 3 <split [32/13]> Bootstrap03
 4 <split [32/13]> Bootstrap04
 5 <split [32/11]> Bootstrap05
 6 <split [32/15]> Bootstrap06
 7 <split [32/13]> Bootstrap07
 8 <split [32/9]>  Bootstrap08
 9 <split [32/12]> Bootstrap09
10 <split [32/14]> Bootstrap10
# … with 15 more rows
> class(dplyr::group_by(bootstraps(mtcars), id))
[1] "grouped_df" "tbl_df"     "tbl"        "data.frame"
```

I would advise closing this for now as I don't think there is much we can do to change this in the short-medium term
