### ISSUE TITLE
Feature request: spatial cross-validation

### ISSUE THREAD

**Issue by MxNl** [tidymodels/rsample#183]
After a rough research on wether it is possible to do cross-validation with spatial data with the `rsample` package I couldn't find any information. Thats why I would like to suggest a function for doing spatial cross-validation similar to `time_series_cv()` or add arguments for coordinate columns in `vfold_cv()`. Thanks for all your work!!!

**Comment by juliasilge** [comment]
A few notes:

- mlr implements spatial resampling, [as described here](https://bookdown.org/robinlovelace/geocompr/spatial-cv.html#spatial-cv-with-mlr)
- The [sperrorest](https://cran.r-project.org/package=sperrorest) package has support for spatial resampling

**Comment by DavisVaughan** [comment]
Also:

- https://github.com/rvalavi/blockCV
- https://github.com/mlr-org/mlr3spatiotempcv

**Comment by topepo** [comment]
See also #32 and #64

**Comment by juliasilge** [comment]
We are working on spatial resampling in our new package [spatialsample](https://github.com/tidymodels/spatialsample).
