### ISSUE TITLE
Identical bootstrap resamples?

### ISSUE THREAD

**Issue by johnaeanderson** [tidymodels/rsample#203]
Hi thanks for generating this really useful package. I'm having a problem however since rsample doesn't seem to be generating different samples. Hopefully I'm doing something wrong that's easy to fix?

## The problem

rsample is generating identical bootstraps 

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

## Reproducible example

```r
library(rsample)
data(wa_churn, package = "modeldata")
set.seed(13)
resample1 <- bootstraps(wa_churn, times = 3)
head(resample1$splits[[1]]$data$total_charges)
#> [1]   29.85 1889.50  108.15 1840.75  151.65  820.50
head(resample1$splits[[2]]$data$total_charges)
#> [1]   29.85 1889.50  108.15 1840.75  151.65  820.50
```

**Comment by topepo** [comment]
To get the bootstrap samples, use the `analysis()` function. The `data` slot is always the same for each split. 

``` r
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.2 ──
#> ✓ broom     0.7.2          ✓ recipes   0.1.15    
#> ✓ dials     0.0.9.9000     ✓ rsample   0.0.8     
#> ✓ dplyr     1.0.2          ✓ tibble    3.0.4     
#> ✓ ggplot2   3.3.2          ✓ tidyr     1.1.2     
#> ✓ infer     0.5.3          ✓ tune      0.1.2     
#> ✓ modeldata 0.1.0          ✓ workflows 0.2.1     
#> ✓ parsnip   0.1.4.9000     ✓ yardstick 0.0.7     
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
data(wa_churn, package = "modeldata")
set.seed(13)
resample1 <- bootstraps(wa_churn, times = 3)
analysis(resample1$splits[[1]]) %>% pull(total_charges) %>% head()
#> [1]  370.65 2723.75  262.05   19.65 4145.90 1248.90
analysis(resample1$splits[[2]]) %>% pull(total_charges) %>% head()
#> [1]  875.35   69.50 1702.90 7344.45 1660.00  395.60
```

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by juliasilge** [comment]
Let us know if you have further questions @johnaeanderson!

I want to make sure you have seen this article on [rsample basics](https://rsample.tidymodels.org/articles/Basics.html) and this one on [working with rsample sets](https://rsample.tidymodels.org/articles/Working_with_rsets.html).
