### ISSUE TITLE
fingerprint as attribute

### ISSUE THREAD

**Issue by topepo** [tidymodels/rsample#212]
The `fingerprint()` function is new and designed to be able to tell when the same resamples were used. For the racing methods in the `finetune` package, the not all of the original resamples may be in the resulting object. For this reason, fingerprinting the results of those functions gives a different hash. 

Should we store the has as an attribute when the resample object is created? This would get around those issues (and is probably a more logical choice).

**Comment by juliasilge** [comment]
Closed in #214
