### ISSUE TITLE
Remove `default_complement()` in favor of `complement.default()`

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/rsample#213]
See https://github.com/tidymodels/rsample/pull/209#discussion_r563773815

**Comment by juliasilge** [comment]
When this is done I will [change how `complement()` is handled in spatialsample](https://github.com/tidymodels/spatialsample/blob/master/R/complement.R).

**Comment by topepo** [comment]
> Ooooh - You could alternatively consider making a `complement.default()` method that would call `default_complement()`. That way you don't have to export `default_complement()`, and @juliasilge would automatically get support for `complement()` in spatialsample.
>
> It would also let you remove all the methods below, except for where you have a specialized implementation where the complement is already stored

Sooo.... it looks like the inheritance structure of `rsplits` is backwards: 

```r
> class(fold_rs$splits[[1]])
[1] "rsplit"      "vfold_split"
```

Looking through the history, this is probably just a mistake. 

I propose:

 1. Make the inheritance right (specific to general in order). 
 2. Check revdeps
 3. Make `complement.default()` _error_ if someone uses it for a non-split object
 4. Make `complement.rsplit()` do what `rsplit_complement()` does (see note below)

Note: Do we need both `rsplit_complement()` and `default_complement()`? I don't think so.

**Comment by hfrick** [comment]
It looks to me like `default_complement()` (similar to `boot_complement()`) has a slightly different job to do: to work directly with arguments `ind` and `n` (while `rsplit_complement()` takes an `rsplit` object) so I'd leave them both.

**Comment by DavisVaughan** [comment]
https://github.com/tidymodels/rsample/pull/216
