### ISSUE TITLE
initial_split() with strata argument behavior

### ISSUE THREAD

**Issue by issactoast** [tidymodels/rsample#217]
## The problem

I was expecting to have the same dimension of dataframe from 
Unexpected size of data frame after initial_split() with strata argument compare to sample_frac()
At least, the original nrow of airquality data is 153 so I guess `airquality_frac2 ` should have 15 or 16.

## Reproducible example

``` r
#sample_frac and sample_n
library(dplyr)
#> 
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

set.seed(2021)
dim(airquality)
#> [1] 153   6

#sample 10% from each month
airquality_frac <- airquality %>% 
    group_by(Month) %>%  
    sample_frac(size = 0.1, replace=FALSE)

library(rsample)

airquality_split <- initial_split(airquality, prop = 0.1,
              strata = "Month")

airquality_frac2 <- training(airquality_split)

dim(airquality_frac)
#> [1] 15  6
dim(airquality_frac2)
#> [1] 18  6
```

**Comment by juliasilge** [comment]
This is because of the stratification and how we use `floor(n * prop)` in `strat_sample()`:
https://github.com/tidymodels/rsample/blob/54e3235a36627b736c4eb3b663eabe6c2061e5e5/R/mc.R#L114-L120

The quantity `airquality$Month` is not uniformly distributed in the sample, especially compared to the overall size, so when we do stratified sampling within each month, we get that result you see.

``` r
library(rsample)
table(airquality$Month)
#> 
#>  5  6  7  8  9 
#> 31 30 31 31 30

initial_split(airquality, prop = 0.1)
#> <Analysis/Assess/Total>
#> <16/137/153>
initial_split(airquality, prop = 0.9)
#> <Analysis/Assess/Total>
#> <138/15/153>

initial_split(airquality, prop = 0.1, strata = Month)
#> <Analysis/Assess/Total>
#> <18/135/153>
initial_split(airquality, prop = 0.9, strata = Month)
#> <Analysis/Assess/Total>
#> <140/13/153>
```

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

We get those results like 13 and 18 from adding up the results of multiplying numbers like `31 * 0.9` and then using `floor()` _within_ the strata.

We don't expect this to have a negative or surprising impact for realistic datasets. Is there a use case where you are finding a problem with this behavior?

**Comment by issactoast** [comment]
Thank you for the explanation! Yes, it wouldn't affect the serious problem but I think this behavior does not coincide with the user's intention. 

`prop` argument is for **the number of samples for analysis** based on what I understand. Since the function uses `floor()` within the strata,  **the number of samples for analysis** should be matched with the `floor()` function expectation.

``` r
library(tidyverse)
library(rsample)

floor(dim(airquality)[1] * 0.1)
#> [1] 15
floor(dim(airquality)[1] * 0.9)
#> [1] 137

floor(table(airquality$Month) * 0.1) %>% sum()
#> [1] 15
floor(table(airquality$Month) * 0.9) %>% sum()
#> [1] 135
```

So I guess the more natural behavior of `initial_split()` for with and without strata for `Month`, should be {15, 137} and {15 and 135}?

**Comment by juliasilge** [comment]
Your last example is a pretty good example of how this happens:

``` r
library(tidyverse)
library(rsample)

initial_split(airquality, prop = 0.1, strata = Month)
#> <Analysis/Assess/Total>
#> <18/135/153>

## this is like the "testing" set
in_size <- floor(table(airquality$Month) * 0.9) %>% sum()
in_size
#> [1] 135

## this is like the "training" set
nrow(airquality) - in_size
#> [1] 18
```

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

We can see why this becomes a bit surprising at very small sample sizes, especially with stratified sampling, but it is a result of needing to deal with whole numbers for indices _within_ the strata.

**Comment by juliasilge** [comment]
Let us know if you have further questions on this behavior! 🙌

**Comment by issactoast** [comment]
Hi @juliasilge, I have been thinking about this issue and stuck for a while. I think I found the code that makes the issue. Could you review the PR and give me your feedback?

**Comment by issactoast** [comment]
Now here is the result of the previous code from my tweak.

``` r
library(rsample)
table(airquality$Month)
#> 
#>  5  6  7  8  9 
#> 31 30 31 31 30

initial_split(airquality, prop = 0.1)
#> <Analysis/Assess/Total>
#> <15/138/153>
initial_split(airquality, prop = 0.9)
#> <Analysis/Assess/Total>
#> <137/16/153>

initial_split(airquality, prop = 0.1, strata = Month)
#> <Analysis/Assess/Total>
#> <15/138/153>
initial_split(airquality, prop = 0.9, strata = Month)
#> <Analysis/Assess/Total>
#> <135/18/153>
```

**Comment by DavisVaughan** [comment]
I'm going to try and summarize this problem _without_ the strata argument first.

``` r
library(rsample)

n_row <- nrow(airquality)
n_row
#> [1] 153

prop_1 <- 0.1

# Approximate number of rows I expect in my analysis set
# By convention, lets round this down to 15
n_row * prop_1
#> [1] 15.3

# But we get 16?
initial_split(airquality, prop = prop_1)
#> <Analysis/Assess/Total>
#> <16/137/153>

# This is because internally we swap `prop` for `1 - prop` and instead compute
# the assessment set indices first. So the following code corresponds to the
# number of rows in the assessment set. Rounded down this gives us 137
n_row * (1 - prop_1)
#> [1] 137.7

# And this is how we got that 16:
n_row - floor(n_row * (1 - prop_1))
#> [1] 16
```

Because our documentation explicitly states:

```
prop | The proportion of data to be retained for modeling/analysis.
```

I do think that I would consider this to be a bug.

I think that the solution in #219 might be the right way to go. I'll give it a review.
