### ISSUE TITLE
Names for each bootstrap sample only exist for stratified sampling

### ISSUE THREAD

**Issue by dchiu911** [tidymodels/rsample#222]
Not sure if this was intended, but when `strata = NULL`, each element of `splits` does not get named the bootstrap index number. I have some code that runs both situations, and it would be nice having those names in the first case. Otherwise I could add something like `names(resample1[["splits"]]) <- seq_along(resample1[["splits"]])`
``` r
library(rsample)
#> Loading required package: tidyr
iris2 <- iris[1:130, ]

resample1 <- bootstraps(iris2, times = 3)
resample2 <- bootstraps(iris2, times = 3, strata = "Species")

resample1$splits
#> [[1]]
#> <130/53/130>
#> 
#> [[2]]
#> <130/40/130>
#> 
#> [[3]]
#> <130/45/130>
resample2$splits
#> $`1`
#> <130/50/130>
#> 
#> $`2`
#> <130/50/130>
#> 
#> $`3`
#> <130/44/130>
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by juliasilge** [comment]
I don't think this is an intentional difference between the two cases. It would be more consistent with the output of other resample functions to have _no_ names. For example, look at the output of `vfold_cv()`:

``` r
library(rsample)

resample1 <- vfold_cv(mtcars, v = 3)
resample2 <- vfold_cv(mtcars, v = 3, strata = am)

resample1$splits
#> [[1]]
#> <Analysis/Assess/Total>
#> <21/11/32>
#> 
#> [[2]]
#> <Analysis/Assess/Total>
#> <21/11/32>
#> 
#> [[3]]
#> <Analysis/Assess/Total>
#> <22/10/32>
resample2$splits
#> [[1]]
#> <Analysis/Assess/Total>
#> <20/12/32>
#> 
#> [[2]]
#> <Analysis/Assess/Total>
#> <22/10/32>
#> 
#> [[3]]
#> <Analysis/Assess/Total>
#> <22/10/32>
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

What would you think if the names were **removed** instead so these were all consistent? I know that's not what you were suggesting here but at least it would be the same in all cases; you could then extend to other resampling types if you wanted.

**Comment by dchiu911** [comment]
Thanks @juliasilge removing the names is fine too so we get consistent outputs

**Comment by topepo** [comment]
It's probably a bad idea to compute on those names; it would be better to use the `id` column(s) (for some resampling methods, there are multiple ID functions). 

Also, there is an S3 method that gives the id value(s) in a tibble:

```r
> map_dfr(resample1$splits, labels)
# A tibble: 3 x 1
  id   
  <chr>
1 Fold1
2 Fold2
3 Fold3
```

**Comment by dchiu911** [comment]
I don't really need to make use of names on the splits, as long as the outputs for both cases of `strata` are consistent

**Comment by DavisVaughan** [comment]
Can you check if you have the CRAN version of rsample 0.0.9? I can't reproduce, and I'm fairly certain I fixed this awhile ago by internally using `split_unnamed()` everywhere

``` r
library(rsample)

iris2 <- iris[1:130, ]

resample1 <- bootstraps(iris2, times = 3)
resample2 <- bootstraps(iris2, times = 3, strata = "Species")

resample1$splits
#> [[1]]
#> <Analysis/Assess/Total>
#> <130/44/130>
#> 
#> [[2]]
#> <Analysis/Assess/Total>
#> <130/50/130>
#> 
#> [[3]]
#> <Analysis/Assess/Total>
#> <130/56/130>
resample2$splits
#> [[1]]
#> <Analysis/Assess/Total>
#> <130/48/130>
#> 
#> [[2]]
#> <Analysis/Assess/Total>
#> <130/50/130>
#> 
#> [[3]]
#> <Analysis/Assess/Total>
#> <130/40/130>
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dchiu911** [comment]
Thanks @DavisVaughan! Sorry I realized I was working in a project-specific library that was using an outdated rsample 0.0.5.
