### ISSUE TITLE
Re-licensing rsample 💫

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/rsample#226]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/rsample/graphs/contributors). 

@ClaytonJY, @Dpananos, @fbchow, @issactoast, @jonkeane, @mattwarkentin, @mdancho84, would you permit us to re-license rsample with the MIT license? If so, please comment "I agree" below.

* [x] [@ClaytonJY](https://github.com/tidymodels/rsample/commits?author=ClaytonJY)  
* [x] [@Dpananos](https://github.com/tidymodels/rsample/commits?author=Dpananos)  
* [x] [@fbchow](https://github.com/tidymodels/rsample/commits?author=fbchow)  
* [x] [@issactoast](https://github.com/tidymodels/rsample/commits?author=issactoast)  
* [x] [@jonkeane](https://github.com/tidymodels/rsample/commits?author=jonkeane)  
* [x] [@mattwarkentin](https://github.com/tidymodels/rsample/commits?author=mattwarkentin)  
* [x] [@mdancho84](https://github.com/tidymodels/rsample/commits?author=mdancho84)

**Comment by mattwarkentin** [comment]
I agree

**Comment by issactoast** [comment]
I agree!

**Comment by ClaytonJY** [comment]
I agree!

**Comment by Dpananos** [comment]
I agree

**Comment by jonkeane** [comment]
I agree

**Comment by mdancho84** [comment]
I agree! 😀

**Comment by fbchow** [comment]
Iagree

**Comment by juliasilge** [comment]
Thank you so much, everyone! 🙏
