### ISSUE TITLE
compatibility with multiple datasets (simulations)

### ISSUE THREAD

**Issue by rkb965** [tidymodels/rsample#243]
## Feature

When comparing modeling approaches on simulated data, it would be wonderful to be able to make use of `workflowsets`. The ability to pass scores of simulated datasets (potentially with correlated observations) to `workflowsets` might come through an `rsample` feature.

My sincere apologies for having no idea how this would work, but I am hopeful that @topepo can run with this and elaborate for others.

Thank you!

**Comment by juliasilge** [comment]
This is an interesting idea @rkb965! Can you give me an example function that would create simulated data sets you would want to iterate over using rsample and workflowsets?

**Comment by juliasilge** [comment]
We recently added some functions for simulations to rsample:
https://rsample.tidymodels.org/dev/reference/sim_classification.html

Let us know if you have further ideas or questions about using rsample for simulations! 🙌
