### ISSUE TITLE
Arguments for sliding_period() calls for object instead of (reactive?) values

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/rsample#249]
Here's a Shiny dashboard with showcase on, so you can see the code there: https://pathos.shinyapps.io/enet_dashboard

***

1) You have to upload some (time series) data first. If you need sample data, here is some code to generate it (then you can upload to the dashboard):

```
# Generate some data that increases over time
dff_generated <- data.frame(yearr = sample(2015:2021, 2190, replace = TRUE),
                 monthh = sample(1:12, 2190, replace = TRUE),
                 dayy = sample(1:29, 2190, replace = TRUE)) |>
  mutate(datee = ymd(paste(yearr, monthh, dayy)),
         weekk = week(datee),
         yy  = sample(10000:20000, 2190, replace = TRUE) + (yearr^2) + (monthh^2) + (weekk^2),
         dummyy = as.factor(round(sample(0:1, 2190, replace = TRUE)))) |>
  filter(!is.na(datee)) |>
  arrange(-desc(datee))

write_csv(dff_generated, 'sample_data.csv')
```

***

2) (if used above sample data) select `yy` as predicted variable, and `datee` as time variable and ID variable.

3) The 'Model' tab gives an error. Although the website does not give verbose error message (probably due to permissions), the error message is `Error: object 'input' not found`

***

I have isolated that it is indeed the last part of uncommented code in `server.R`, this part here:

```
folds = dff() |>
            sliding_period(lookback = input$lookback, # if Inf, then it's chain
                           period = input$period,
                           index = input$var_time,
                           #assess_stop = 1L, # include how many 'periods' in the future
                           every = input$every, # group how many 'periods' together
                           step = input$step, # how many 'periods' * 'every' to move the window (?)
                           skip = input$skip)
```

Interestingly enough, `sliding_period()` seems to call for an object, not a value.

**Comment by DavisVaughan** [comment]
It seems like there might be some issue with the environment `renderPlotly()` (which is what `sliding_period()` is called from) uses and the one `input` lives in.

The `index` argument of `sliding_period()` is ideally meant to be a bare column name, like `sliding_period(data, index = foo)` where `foo` is a column in `data`. I think that is where the problem is coming from.

Can you try tweaking your code like this? This turns the character `index` into a symbol, and then injects it as something that hopefully `sliding_period()` can find

``` r
library(modeldata)
library(rsample)
data("Chicago")

# Mimic shiny input
input <- list(var_time = "date")

# Try adding this line
var_time_sym <- rlang::sym(input$var_time)

sliding_period(
  Chicago,
  index = {{ var_time_sym }}, # And then input the index like this
  "year",
  lookback = 2,
  assess_stop = 1
)
#> # Sliding period resampling 
#> # A tibble: 13 x 2
#>    splits             id     
#>    <list>             <chr>  
#>  1 <split [1074/366]> Slice01
#>  2 <split [1096/365]> Slice02
#>  3 <split [1096/365]> Slice03
#>  4 <split [1096/365]> Slice04
#>  5 <split [1095/366]> Slice05
#>  6 <split [1096/365]> Slice06
#>  7 <split [1096/365]> Slice07
#>  8 <split [1096/365]> Slice08
#>  9 <split [1095/366]> Slice09
#> 10 <split [1096/365]> Slice10
#> 11 <split [1096/365]> Slice11
#> 12 <split [1096/365]> Slice12
#> 13 <split [1095/241]> Slice13
```

<sup>Created on 2021-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by PathosEthosLogos** [comment]
Thanks @DavisVaughan

I see. That's an interesting problem to have actually. I tried it with `rlang::sym()` so here is what it looks like after your suggested edit:

```
folds = dff() |>
            sliding_period(lookback = rlang::sym(input$lookback), # if Inf, then it's chain
                           period = rlang::sym(input$period),
                           index = rlang::sym(input$var_time),
                           #assess_stop = 1L, # include how many 'periods' in the future
                           every = rlang::sym(input$every), # group how many 'periods' together
                           step = rlang::sym(input$step), # how many 'periods' * 'every' to move the window (?)
                           skip = rlang::sym(input$skip))
```

Now a new error pops up: `Error: Only strings can be converted to symbols`

So I put quotes around them (e.g. `rlang::sym('input$lookback')`), but now getting new error: `Input must be a vector, not a symbol.`

So I tried to coerce it to a vector using `as.vector()` (e.g. `as.vector(rlang::sym('input$lookback'))`)

Just tried these simple potential solutions but no luck. Interesting that your solutions works though. Hmm

**Comment by DavisVaughan** [comment]
Please only use it for `index`. You should also create an actual variable called `var_time_sym`. Like:

```r
var_time_sym = rlang::sym(input$var_time)

folds = dff() |>
            sliding_period(lookback = input$lookback, # if Inf, then it's chain
                           period = input$period,
                           index = {{ var_time_sym }},
                           #assess_stop = 1L, # include how many 'periods' in the future
                           every = input$every, # group how many 'periods' together
                           step = input$step, # how many 'periods' * 'every' to move the window (?)
                           skip = input$skip)
```

**Comment by PathosEthosLogos** [comment]
Uuu that fixed it, thanks

Interesting solution, I'll have to look into it after I tackle the next bug
