### ISSUE TITLE
accumulative testing data : Rolling Origin Forecast Resampling

### ISSUE THREAD

**Issue by Shafi2016** [tidymodels/rsample#265]
Hello @dgrtwo and @juliasilge ,  I am using rolling-origin. Say we are forecasting a six-step ahead forecast. Currently, it is fixed on six periods as given in this picture. On the testing data, it uses the fixed six-step ahead forecast. I want to make the testing part cumulative, 6, 12, 18, 24, 30, 36 and so. 
 
![image](https://user-images.githubusercontent.com/56795978/140555434-d2059f57-d996-44d5-aa72-077ee601c775.png)
I want to roll over the slices as shown below.  I am using R rolling_origin () to do the rolling step forecasting. Currently, the "cumulative" option accumulates only training the data. And test data (assess) remains constant as shown below :

I am looking for a way, where we could accumulate test data as well (move six-step ahead) and roll over the different slices with some interval. In other words, I want to perform rolling windows only over slices as given below.
 
![image](https://user-images.githubusercontent.com/56795978/140653411-4650a892-99a8-4ffa-b682-831a6b3fa7c2.png)

```
library(tidymodels)
library(modeltime)
library(modeltime.resample)
library(tidyverse)
library(timetk)


resample_spec <- rolling_origin(
  data        = m750,
  initial    = 50,
  assess     = 6,
  cumulative = TRUE,
  skip       = 1,
  overlap    = 0
)

resample_spec %>% tail()


resamples_fitted <- m750_models %>%
  modeltime_fit_resamples(
    resamples = resample_spec,
    control   = control_resamples(verbose = FALSE)
  )

```

**Comment by juliasilge** [comment]
Hello there, @Shafi2016! Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. It's not clear to me from what you have posted what you are trying to do, and what is not working.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by Shafi2016** [comment]
Thank you @juliasilge.  Here reproducible example.

```
library(tidymodels)
library(Quandl)
library(tidyverse)
library(timetk)

df1 <- Quandl(code = "FRED/PINCOME",
              type = "raw",
              collapse = "monthly",
              order = "asc",
              end_date="2017-12-31")
df2 <- Quandl(code = "FRED/GDP",
              type = "raw",
              collapse = "monthly",
              order = "asc",
              end_date="2017-12-31")

per <- df1 %>% rename(PI = Value)%>% select(-Date)
gdp <- df2 %>% rename(GDP = Value) 

data <- cbind(gdp,per)

data1 <- tk_augment_differences(
  .data = data,
  .value = GDP:PI,
  .lags = 1,
  .differences = 1,
  .log = TRUE,
  .names = "auto") %>%
  select(-GDP,-PI) %>%
  
  rename(GDP = GDP_lag1_diff1,PI = PI_lag1_diff1) %>% 
  drop_na()


lag_period <- c(1:10)

data_pre_full <- data1 %>%
     
  
  # add lags----
tk_augment_lags(
  .value =  GDP : PI   , 
  .lags = lag_period) 
data_prepared_tbl <-   data_pre_full %>%
  
  filter(!is.na(GDP)) %>% 
  dplyr::select(-GDP : -PI)  %>%  
  drop_na()

resample_spec <- rolling_origin(
  data        = data_prepared_tbl,
  initial    = 100,
  assess     = 6,
  cumulative = TRUE,
  skip       = 1,
  overlap    = 0
)
str(resample_spec)
a <- resample_spec %>%
  mutate(data = map(splits, assessment)) %>%
  unnest(data)

resample_spec %>% head()
```
![image](https://user-images.githubusercontent.com/56795978/140955238-a58f53ad-facd-46c4-8815-c03f46fc0dab.png)

The current version of the rolling_origin function gives the fixed number of assessments (say 6 as given above). I am looking to do  "assess" or test data as below:

![image](https://user-images.githubusercontent.com/56795978/140956529-57811d19-fadf-40ae-a320-c688a4555fb0.png)
  I want to perform rolling windows only over slices (testing part).  As you have shown, slice01 start from (6 steps ahead forecast),   slice02 (12), we keep increasing six step up to slice05. Then we start from slice02, (12), move six-step ahead and so.

**Comment by topepo** [comment]
Can you elaborate a little more with this minimal example? Suppose you had 1:14 and initially modeled with 8 then held out 2. 

```
resample 1   analysis: 1:8
resample 1 assessment: 9:10
```

What would resample 2 be? Maybe this? 

```
resample 1   analysis: 1:10
resample 1 assessment: 11:14
```

That increases the assessment set but, since the analysis set is rolling, it would expand too and encompass some of the previous assessment set. Do you want the analysis set to stay static? 

Overall, we generally prevent the assessment data being exposed to the analysis set and vice-versa. We would avoid any overlap between the two.

**Comment by Shafi2016** [comment]
Thank you so much @topepo 

If we want to forecast six-step ahead.

Window1/Slice1,   training : 1 to  100,
                     Testing    101-102,103, 104,105,106


Window2/Slice2,   Training    2: 101,
                      Testing    102,103,104,105,106, (predicted values from window1), 107,108,........112.

   
Window3/Slice3,   Training    3: 102,
                      Testing    102,103,104,105,106,........ 112 (predicted values from window1 and window 2), 113,114,......118.


Window4/Slice4,   Training    3: 102,
                      Testing    102,103,104,105,106,........ 112........118 (predicted values from window1, window 2 and window3), 119,120,121,.....124.

Window5/Slice5,   Training    4: 104,
                      Testing    102,103,104,105,106,........ 112........130 (predicted values from window1, window 2 and window3 and window4), .



 


This the recursive forecasting with rolling strategy.  Isn’t the first step of getting into subsamples is superfluous.  The recursive forecasting formulation usually give us bad forecasting though.

**Comment by topepo** [comment]
I don't think that we would write a function for that since the training and testing data overlap. You might be able to do it with `sliding_index()`.

**Comment by Shafi2016** [comment]
We take the predicted values (from previous windows) to forecast ahead like in window 2 we take predicted from window 1 and forecast on test data. Do you think, we still have data overlap between the training and testing.
Window1/Slice1,
training : 1 to 100,
Testing : 101-102,103, 104,105,106

Window2/Slice2,

Training 2: 101,
Testing 102,103,104,105,106, (predicted values from window1), 107,108,........112.

**Comment by Shafi2016** [comment]
Thank you @topepo  and @juliasilge ,

We can get too many overlapping can overlap across the slices when using ` rolling_origin`. Is there a way to avoid it or decrease the number of overlapping forecasts? If you please excel sheet, we find too many overlapping tests.assess values.  Please let me know.
[Rolling_origin_step6.xlsx](https://github.com/tidymodels/rsample/files/7514493/Rolling_origin_step6.xlsx)

**Comment by juliasilge** [comment]
For our approach to resampling, it is not a problem that the same observations are in the test sets in different resamples but it *is* a problem for the same observations to be in both the training and test sets in the same resample.  We design to make this not possible, to protect against data leakage and overly optimistic evaluation of models. The predictions from one resample can't go into another resample because they must be independent of each other.

To understand our philosophy on data splitting and resampling, you might check out:

- https://www.tmwr.org/splitting.html
- https://www.tmwr.org/resampling.html
- https://www.tidymodels.org/learn/models/time-series/

**Comment by Shafi2016** [comment]
Thank you once again! Probably I could not explain my question. Technically there is no issue I understand. Here a snapshot from the above excel sheet.  If we look at slice01 and slice02. We get the same test values across the indepdent slices e.g. ( in slice02
2017-03-01
2017-04-01
2017-05-01
2017-06-01
from slices one. We have 04 observation are similar between slice01 and slice02 . So Is there a way to minimize the similar sample test values across the different slices. I want to draw the rolling RMSE, when I remove similar dates, I get only a few observation. 

![image](https://user-images.githubusercontent.com/56795978/141234564-de7d7f62-cb99-4b39-8977-9b68382d6acf.png)

**Comment by topepo** [comment]
I think that we are having trouble understanding. Being more explicit or describing it a different way would be helpful. 

I think that you are wondering if there is an issue with two test samples having similar observations. Generally, that is not an issue. In a rolling statistic you typically have some overlap form index-to-index.

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
