### ISSUE TITLE
blocking/grouping documentation

### ISSUE THREAD

**Issue by nick-youngblut** [tidymodels/rsample#274]
It appears that the [rsampling docs](https://www.tidymodels.org/start/resampling/) don't contain info on blocking/grouping, as is described in the [mlr package docs](https://mlr.mlr-org.com/articles/tutorial/resample.html) or the [scikit-learn package docs](https://scikit-learn.org/stable/auto_examples/model_selection/plot_cv_indices.html#sphx-glr-auto-examples-model-selection-plot-cv-indices-py). It would be helpful to have that info in the "get started" docs, given how common the need for blocking/grouping is in ML.

**Comment by juliasilge** [comment]
I think all we really have right now on grouping is in the documentation for `group_vfold_cv()`:
https://rsample.tidymodels.org/reference/group_vfold_cv.html

I'll say this is related to #207 where we discuss plans to support grouping more thoroughly.
