### ISSUE TITLE
Reversing analysis and assessment splits

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/rsample#284]
Hi,

I use the `group_vfold_cv()` function a lot, but I have recently been needing to reverse the analysis and assessment splits. For example, lets say you have 3 groups, `group_vfold_cv()` would create three folds, whereby within each fold 2 groups are used for training, and one is held aside for testing. I would like to do the opposite, where one group is used for training, and the remaining groups are used for testing.

I don't think this is possible using `make_splits()`, unless I'm just doing it incorrectly. Would you ever consider supporting this resampling scheme? If not, is it possible for me to create these kinds of splits using the existing `rsample` machinery?

**Comment by mattwarkentin** [comment]
Figured out how to do it manually, thought it might be worth sharing:
``` r
library(tidyverse)
library(rsample)
library(palmerpenguins)

sets <- list(
  list(
    analysis = filter(penguins, species == 'Adelie'),
    asessment = filter(penguins, species != 'Adelie')
  ),
  list(
    analysis = filter(penguins, species == 'Chinstrap'),
    asessment = filter(penguins, species != 'Chinstrap')
  ),
  list(
    analysis = filter(penguins, species == 'Gentoo'),
    asessment = filter(penguins, species != 'Gentoo')
  )
)

map(sets, ~ make_splits(.x[[1]], .x[[2]])) %>% 
  manual_rset(ids = c('Adeile', 'Chinstrap', 'Gentoo'))
#> # Manual resampling 
#> # A tibble: 3 × 2
#>   splits            id       
#>   <list>            <chr>    
#> 1 <split [152/192]> Adeile   
#> 2 <split [68/276]>  Chinstrap
#> 3 <split [124/220]> Gentoo
```

**Comment by mattwarkentin** [comment]
@mikemahoney218 @juliasilge Now that group sampling is on the verge of being supported for many resampling methods via #313, #315, and #316, I am wondering if it might be a good time to revisit this feature/issue.

I had a thought today that perhaps something like `reverse_splits()` could be an S3 generic that can accept `rset` or `rsplit` objects and reverse the splits? S3 methods could be defined for the various resampling methods for which this applies. Thoughts?

Something like:
```r
data |>
  group_vfold_cv(group = var) |>
  reverse_splits()
```

Just thinking out loud...

**Comment by juliasilge** [comment]
This makes me think of #79 and the idea of taking an existing rset and doing something to it (in that case, reshuffling it). It could be interesting to think through what kinds of operations folks might need to take on an existing object.

**Comment by mattwarkentin** [comment]
Agreed! Originally I thought this was something that should be implemented as an argument to the resampling method, but maybe it makes sense to think of various post-hoc procedures that could be done (e.g. reversing, reshuffling, etc.).

**Comment by mattwarkentin** [comment]
Note to self/someone, for reversing, I think you would only need to develop/maintain methods for lower-level `*_split()` objects (i.e., `boot_split`, `vfold_split`, `mc_split`) and then for `rset` objects you would just loop over the relevant split method. Thinking out loud...
