### ISSUE TITLE
`nested_cv` throws error with `initial_split` outside and `vfold_cv` inside

### ISSUE THREAD

**Issue by wkdavis** [tidymodels/rsample#286]
I'm not familiar with the distinction between `initial_split()` and `validation_split()`, but I am trying to conduct an initial 50/50 train/test split, then run CV on the training set. When I use `nested_cv()` I get an error if I use `initial_split()` as the `outside` method, but I don't get the error for `validation_split()`. Is there a difference between the two, or is there a bug somewhere in `nested_cv()`? Thank you!

``` r
library(mlbench)
library(tidymodels)

sim_data <- function(n) {
  tmp <- mlbench.friedman1(n, sd = 1)
  tmp <- cbind(tmp$x, tmp$y)
  tmp <- as.data.frame(tmp)
  names(tmp)[ncol(tmp)] <- "y"
  tmp
}

set.seed(9815)
train_dat <- sim_data(100)


results <- nested_cv(train_dat, 
                     outside = validation_split(prop = .5), 
                     inside = vfold_cv(repeats = 3))

results <- nested_cv(train_dat, 
                     outside = initial_split(prop = .5), 
                     inside = vfold_cv(repeats = 3))
#> Error in UseMethod("mutate"): no applicable method for 'mutate' applied to an object of class "c('mc_split', 'rsplit')"
```

<sup>Created on 2022-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by juliasilge** [comment]
[`nested_cv()`](https://rsample.tidymodels.org/reference/nested_cv.html) is for double _resampling_, which means that we have to use two resampling methods. In tidymodels, [`initial_split()` creates a single training/test split](https://rsample.tidymodels.org/reference/initial_split.html) but does not create resamples. On the other hand, in tidymodels a [`validation_split()` is a special kind resampling](https://rsample.tidymodels.org/reference/validation_split.html) that only has one resample. You can [read more here about a validation split](https://www.tmwr.org/resampling.html#validation) and how we treat it as just another type of resample. Think of a validation split as the same kind of thing as cross validation and bootstrap resampling, whereas making an initial training/testing split is different.

**Comment by wkdavis** [comment]
Understood, that makes sense. Thank you!
