### ISSUE TITLE
Consider keeping the `rset` class after slicing with `[`

### ISSUE THREAD

**Issue by dfalbel** [tidymodels/rsample#287]
Especially when using the `sliding_` resamples it might be useful to be able to slice the resample set so we can use a few of them for cross validation and others exclusively for testing.

For example:

``` r
library(modeldata)
library(rsample)
data("Chicago")


resamples <- sliding_period(
  Chicago,
  date,
  "year",
  lookback = 5,
  assess_stop = 1
)

cv_resamples <- resamples[1:7,]
test_resamples <- resamples[9:10,]

class(cv_resamples)
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2022-04-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Initial 'time-splitting' only might not be desirable because you then the 'test' set wouldn't have the other observations.
What do you think?

**Comment by DavisVaughan** [comment]
Why would you have _resamples_ reserved purely for testing? Shouldn't it just be a standard data frame? i.e. for that post-cv testing I don't think you should need to fit any models, it should just be about making predictions at that point, right? So you don't need analysis/assessment for that.

In general, we thought hard about the semantics of how the rset class should behave when slicing with things like `[` and decided that if you lose any of the rows then it doesn't meet the criteria of being a valid rset anymore.

**Comment by dfalbel** [comment]
The use case I have in mind is a time-series problem where I have my dataset divided like below:

![image](https://user-images.githubusercontent.com/4706822/163243685-b0376000-4b0d-47dd-bad5-6ce19f139e1b.png)

I'd like to tune hyper parameters on the first and second slice. When testing on Slice 3, (even if it's only for prediction) it should be able to see the full dataset except for the last rectangle. Ideally, I'd re-fit this model with the full data for every slice.

**Comment by DavisVaughan** [comment]
Why not do something like this?
![Untitled](https://user-images.githubusercontent.com/19150088/163245845-c79adc09-1a08-4ce1-b581-035dc9ef9eec.png)

**Comment by dfalbel** [comment]
In theory yes, although it's not very convenient if I want to use more than 1 period for testing and would like to refit the model for every period.

Which might not make sense for yearly forecasts but make sense for daily data where outliers are very likely, so better not rely on a single day of testing. My goal was to use `fit_resamples` instead of `last_fit` for that.

**Comment by DavisVaughan** [comment]
In the spirit of keeping the number of issues in rsample down, I'm going to close this as there seems to be at least some way to work around it and it hasn't come up before. We will keep it in mind if it comes up again from someone else. Thanks!
