### ISSUE TITLE
Note: Using an external vector in selections is ambiguous.

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/rsample#294]
## The problem

I'm having a really hard time finding the source or fitting a reprex (sorry! I'll keep trying), but: rsample generates the following message when using `strata` or `group` arguments for the first time:

```
"Message"
"  Note: Using an external vector in selections is ambiguous."
"  i Use `all_of(group)` instead of `group` to silence this message."
"  i See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>."
"  This message is displayed once per session."
```

You can see the message in rsample's CI here:

https://github.com/tidymodels/rsample/runs/6760867450?check_suite_focus=true#step:6:182

But I don't think I understand how to capture whatever generates these messages in a reprex.

**Comment by EmilHvitfeldt** [comment]
Small detective work 🕵️ 

I think this message comes from 

https://github.com/tidymodels/rsample/blob/978cd2647fa74303c6a3acbc3f96ce1017d84c07/tests/testthat/test-initial.R#L3

Which when runs encounters this code

https://github.com/tidymodels/rsample/blob/978cd2647fa74303c6a3acbc3f96ce1017d84c07/R/initial_split.R#L35-L40

`!missing(strata)` is equal to `FALSE`, so `strata` is set to `NULL`. Later inside `mc_cv()`, `!missing(strata)` is equal to `TRUE` and  `tidyselect::vars_select()` complains

https://github.com/tidymodels/rsample/blob/978cd2647fa74303c6a3acbc3f96ce1017d84c07/R/mc.R#L54-L57

I don't understand why `!missing(strata)` does different things different places. And should be even use `missing()`? I was under the understanding that `is.null()` would be better here

**Comment by juliasilge** [comment]
I looked at this today, and it's happening because `strata` can be a bare name or `NULL`, and when `initial_split()` calls `mc_cv()`, it passes in `strata = NULL`, which is not missing, so then `mc_cv()` tries to `tidyselect::vars_select()` with `NULL`.
