### ISSUE TITLE
Post 1.0.0 release, move to dplyr 1.0.0

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/rsample#305]
After this 1.0.0 release (i.e. the one _after_), let's require dplyr >= 1.0.0 and handle the move from `compat_dplyr-old.R` to only needing the new version.

**Comment by DavisVaughan** [comment]
i already see this? https://github.com/tidymodels/rsample/blob/225f760c8bd9e131413a97e322c36e3423afc8fc/DESCRIPTION#L21

**Comment by DavisVaughan** [comment]
Which is also in the CRAN version of rsample 😅

**Comment by juliasilge** [comment]
HAHA oh gosh 🙈 

@DavisVaughan when [it says "deprecate" here](https://github.com/tidymodels/rsample/blob/main/R/compat-dplyr-old.R) does that literally mean deprecate that code with `.Deprecated` or something, or just delete it? (I understand about moving the tests, not deleting them.)

**Comment by DavisVaughan** [comment]
I am fairly certain it just means delete it. Happy to review a PR to make sure we remove it all
