### ISSUE TITLE
Using manually created cross validation object

### ISSUE THREAD

**Issue by sametsoekel** [tidymodels/rsample#307]
In order to create a cross-validation object consisting of folds that I chose myself, to simulate the output provided by the `rsample` package, I set up the `nest()` function of `tidyr` as follows;

```
suppressPackageStartupMessages({
    library(tidymodels)
    library(dplyr)
    library(tidyr)
})

my_cv <- iris %>%
mutate(Fold = case_when(row_number() %in% 1:50 ~ 'Fold1',
                        row_number() %in% 51:100 ~ 'Fold2',
                        row_number() %in% 101:150 ~ 'Fold3')) %>%
group_by(Fold) %>%
nest() %>%
ungroup
```

But when I checked the cross validation object created by `rsample` again, I realized that I could not provide its properties such as object class, object attributes.

How is it possible for me to use a cross-validation object with `tune_grid()`, whose folds I have determined according to different conditions, as in the example or not?

Thanks in advance.

**Comment by juliasilge** [comment]
You can use `manual_rset()` like this:

``` r
library(rsample)

indices <- list(
    list(analysis = 51L:150L, assessment = 1L:50L),
    list(analysis = c(1L:50L, 101L:150L), assessment = 51L:100L),
    list(analysis = 1L:100L, assessment = 101L:150L)
)

splits <- purrr::map(indices, make_splits, data = iris)
splits
#> [[1]]
#> <Analysis/Assess/Total>
#> <100/50/150>
#> 
#> [[2]]
#> <Analysis/Assess/Total>
#> <100/50/150>
#> 
#> [[3]]
#> <Analysis/Assess/Total>
#> <100/50/150>

manual_rset(splits, paste0("Fold", 1:3))
#> # Manual resampling 
#> # A tibble: 3 × 2
#>   splits           id   
#>   <list>           <chr>
#> 1 <split [100/50]> Fold1
#> 2 <split [100/50]> Fold2
#> 3 <split [100/50]> Fold3
```

<sup>Created on 2022-06-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sametsoekel** [comment]
Thanks, that was what I look for.
