### ISSUE TITLE
Should we pull `balance` out of `group_vfold_cv()` for 1.0?

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/rsample#309]
I'm losing a bit of my confidence that `balance`, as it currently exists in `group_vfold_cv()`, is going to be what we want to support long-term. Given that, should we pull the `balance` option from this coming release, and then add it back when we implement the rest of our grouping?

There are two main challenges with the current approach:

1. Right now, the two options (`groups` and `observations`) don't need to incorporate any arguments other than an index of the data, a corresponding vector of group IDs, and `v`. As we expand to `mc_cv()` and `initial_split()`, we're going to need to find a way to incorporate `prop` as an argument, and I think we want to incorporate `strata` as well (to assign groups to folds based on stratified variables). Having a character vector of options for `balance` makes dealing with this a bit challenging without introducing complex dependencies between arguments.
2. `balance = "observations"` is deterministic, and I don't know if we _like_ that. At the very least, it means that bringing it to things like `mc_cv()` is difficult, since we very much _don't_ want those to be deterministic samples.

I've got some thoughts about how to approach this, but I don't think they're going to make it by the 1.0 release. How would we feel about not introducing `balance` in this release, and instead including it with a broader `group` release?

**Comment by juliasilge** [comment]
These are great points, and I am totally on board. 👍
