### ISSUE TITLE
Grouped resamples are inconsistently of a `group_*` class

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/rsample#318]
After #315 and #316, we'll have four separate grouped resampling functions:

+ `group_vfold_cv()`, the oldest, produces rsplits of class `c("group_vfold_split", "rsplit")` and rsets of class `c("group_vfold_cv", "rset")`
+ `group_mc_cv()`, patterned after that, produces rsplits of class `c("grouped_mc_split", "rsplit")` and rsets of class `c("group_mc_cv", "rset")`
+ `group_bootstraps()` (#316) produces rsplits of class `c("group_boot_split", "boot_split", "rsplit")` and rsets of class `c("group_bootstraps", "bootstraps", "rset")` (the rsplit inconsistency is my mistake, and is due to working on #315 first)
+ `group_initial_split()` (#315) produces rsplits of class `c("initial_split", "mc_split", "rsplit")`, patterned off of `initial_time_split()`
+ `group_validation_split()` (#315) produces rsplits of class `c("val_split", "rsplit")` and rsets of class `c("validation_split", "rset")`, patterned off of `validation_time_split()`

This is a lot of variation, and as Julia mentioned in #315, we should investigate a way to make this be more consistent. 

Personally, I like the maximalist position I accidentally wound up with in `group_bootstraps()`: grouped resamples should subclass the non-grouped version, keeping _all_ of their classes and adding a `group_` class on top. I can't think of any case where a method _should_ dispatch on, e.g., `vfold_cv()` but error on grouped outputs. The closest I can think of is #79, but in that situation you should provide a `group_vfold_cv()` method as well, not just error.

**Comment by juliasilge** [comment]
Let's remember to check and update the classes in `compat-vctrs.R` and `compat-vctrs-helpers.R` as part of this.

**Comment by mikemahoney218** [comment]
I'm wondering if we should subclass `rset` as well, so that all grouped resamples produce an object with classes `c("group_rset", "rset")`. That would let functions like what's proposed in #79 error on all grouped objects as a class, rather than have it be specific to each object type.
