### ISSUE TITLE
Add new grouped resampling to vctrs compatibility

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/rsample#320]
It looks like I missed the fact that we need to add the new grouped resampling functions to `compat-vctrs-helpers.R`. Related to #315

**Comment by mikemahoney218** [comment]
Hmm -- the new functions in #315 don't add new classes (#318), so I didn't think they needed to be added explicitly. For example, `validation_time_split()` isn't in `rset_subclasses`.

**Comment by juliasilge** [comment]
Ah gosh, yep, these classes are getting to be a real inconsistent mess. 🥵
