### ISSUE TITLE
Calling `assessment()` on a `permutations` gives a confusing error

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/rsample#321]
Related: I am now seeing that the error thrown when calling `assessment()` on a `permutations` object is not correct:
``` r
library(rsample)

p <- permutations(mtcars, cyl)

assessment(p$splits[[1]])
#> Error in `as.data.frame()`:
#> ! There is no assessment data set for an `rsplit` object with class `rsplit`.
```

It should read something like:
> #> ! There is no assessment data set for an `rsplit` object from a `permutations` set.

Or something along those lines...

_Originally posted by @mattwarkentin in https://github.com/tidymodels/rsample/pull/319#issuecomment-1170492817_

**Comment by juliasilge** [comment]
We also do need to add `permutations()` to the vctrs compatibility files. I _think_ it should just act like other rsets? In terms of binding rows/columns? Worth a little thought, though.
