### ISSUE TITLE
`group_vfold_cv()` should have a `repeats` argument

### ISSUE THREAD

**Issue by mikemahoney218** [tidymodels/rsample#327]
## Feature

As mentioned by @mattwarkentin , `group_vfold_cv()` is currently the only function that's not equivalent to its non-group version (other than stratification), because right now `group_vfold_cv()` does not have a `repeats` argument.

I think it would be nice for `group_vfold_cv()` to have a `repeats` argument. That said, I think we should probably throw an error in _both_ functions when `v == max_v` (either `nrow(data)` or `length(unique(data$group))`), because that means you're going to have identical repeats, which strikes me as undesirable.

**Comment by juliasilge** [comment]
Yes, sounds good. 👍 Let's:

- add a `repeats` argument
- throw an error to protect against identical repeats
