### ISSUE TITLE
`group_bootstraps()` sometimes errors with 0 rows in `compat-vctrs-helpers.R`

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/rsample#331]
See here for an example where this is failing:
https://github.com/tidymodels/rsample/runs/7155341170?check_suite_focus=true#step:6:134

**Comment by mikemahoney218** [comment]
I've got the fix for this in #329 but can put it up as a separate PR since that one is a little ways away

**Comment by juliasilge** [comment]
Yeah, that will be good so we don't have to rerun checks here and there.
