### ISSUE TITLE
Merge additional samplers implemented in the`resamplr` package?

### ISSUE THREAD

**Issue by jrnold** [tidymodels/rsample#34]
In https://github.com/jrnold/resamplr, I had implemented quite a few samplers extending the `resample` objects from the `modelr` package. This included: bootstrap, jackknife, random test/train sets, k-fold cross-validation, leave-one-out and leave-p-out cross-validation, time-series cross validation, time-series k-fold cross validation, permutations, rolling windows. They also generally respected grouped data frames from clustered or stratified sampling. However, my package seems redundant now. I was wondering if you were interested in me incorporating any samplers from `resamplr` that aren't in `rsample` if I were to submit a pull request.

**Comment by topepo** [comment]
That would be great! Some of them already exist (and please provide feedback if you have any). The `grouped_df` approach is pretty good too. 

Let me know if you need a walkthrough on the internals. I deviated from the `modelr` approach a bit but hopefully the sources are readable in that respect. If not, let me know.

**Comment by jrnold** [comment]
I was turning back to this after a while. It looks like there is still some room for it. In addition to implementing the remaining algorithm, I was thinking about two  additional ideas on how to do this.

1.  Create a lower-level package that implements (most) of these methods but the functions take as an inputs only the number of observations to sample from. These functions can be reused to bootstrap data frames, lists, vectors, etc. 
2. Use quosures to explicitly reference the object to be sampled from, instead of list objects and relying on implicit copy-on-modify semantics.

**Comment by jrnold** [comment]
I've refactored object agnostic resampling functions into [mlspearer](https://github.com/jrnold/mlspearer). All of these functions are of the type `f(n, ...)` where `n` is an integer scalar with the number of items, and the return value is a list of index objects (usually a list of one or more integer vectors). I haven't added groupings, but they're next.

> Use quosures to explicitly reference the object to be sampled from, instead of list objects and relying on implicit copy-on-modify semantics.

>> Can you elaborate and maybe provide an example of what that gets us?

Honestly, I don't really know and this may be more motivated by shiny-new-thing, than practical requirements. Is there a case when copy-on-modify would fail but quosures wouldn't? Would one make it easier to parallelize? I'd have to think about it and experiment.

**Comment by topepo** [comment]
Keep in mind that `modelr` is quasi-deprecated in favor of `rsample` and other new packages. 

> Is there a case when copy-on-modify would fail but quosures wouldn't?

We don't really do any copy-on-modify until the resampled version is used for analysis, i.e. an `rset` object has no extra overhead for having `data` slots in every row. I don't see any way around the copy-on-modify at the end. Perhaps I'm missing the gist of your point.

**Comment by jrnold** [comment]
> Keep in mind that modelr is quasi-deprecated in favor of rsample and other new packages.

Agreed. I'm no longer using modelr.  mlspearer is independent of modelr and is for a more general use than just data frames. 

> We don't really do any copy-on-modify until the resampled version is used for analysis, i.e. an rset object has no extra overhead for having data slots in every row. I don't see any way around the copy-on-modify at the end. Perhaps I'm missing the gist of your point.

It's not the creation of the new object at the end that I'm wondering about. The `rset` object has only the overhead of a pointer to the object in the`data` slot because of copy-on-modify. I'm wondering if there are situations in which the object referenced in the `data` slot is changed that will implicitly result in the rset objects storing copies.  I'm wondering if having the `data` slot be a quosure (expression + environment to evaluate it in) would be more robust or explicit.

**Comment by topepo** [comment]
> It's not the creation of the new object at the end that I'm wondering about. The `rset` object has only the overhead of a pointer to the object in the `data` slot because of copy-on-modify. I'm wondering if there are situations in which the object referenced in the `data` slot is changed that will implicitly result in the rset objects storing copies.  I'm wondering if having the `data` slot be a quosure (expression + environment to evaluate it in) would be more robust or explicit.

@hadley or @lionel- might have some thoughts on that.

**Comment by topepo** [comment]
Here's a prototype `rsample` function that I created for leave-p-out from `ramsleep`. This seems pretty easy to me. If you think `ramsleep` is the appraoch that you'll take, let me know and I'll make an `rsample` branch for the translation functions to go between `ramsleep -> rsample`

```r
#' Leave-p-Out Cross-Validation
#'
#' Leave-p-Out Cross-Validation Leave-p-out (LPO) cross-validation
#'  takes all combinations that do not include `p` data points in
#'  the analysis set.
#'
#' @inheritParams vfold_cv
#' @param p The number of data points to leave out of each resample. 
#' @export
#' @return An tibble with classes `lpo_cv`, `rset`, `tbl_df`, `tbl`,
#'  and `data.frame`. The results include a column for the data
#'  split objects and a column called `id` that has a character
#'  string with the resample identifier.
#' @examples
#' lpo_cv(mtcars, p = 2)
#' @export
lpo_cv <- function(data, p = 2, ...) {
  
  split_objs <- lpo_splits(data = data, p = p)
  
  ## We remove the holdout indicies since it will save space and we can 
  ## derive them later when they are needed. 
  split_objs$splits <- map(split_objs$splits, rm_out)
  
  lpo_att <- list(prop = p)
  
  new_rset(splits = split_objs$splits, 
           ids = split_objs$id, 
           attrib = lpo_att, 
           subclass = c("lpo_cv", "rset")) 
}

# Get the indices of the analysis set from the assessment set
lpo_complement <- function(ind, n) {
  list(analysis = setdiff(1:n, ind),
       assessment = ind)
}

#' @importFrom purrr map
#' @importFrom tibble tibble
#' @importFrom ramsleep crossv_lpo
lpo_splits <- function(data, p = 2) {
  n <- nrow(data)
  rs <- ramsleep::crossv_lpo(n, size = p)
  indices <- map(rs,
                 function(x)
                   list(
                     analysis = setdiff(1:x$n, x$out_id),
                     assessment = x$out_id
                   ))
  split_objs <-
    purrr::map(indices, make_splits, data = data, class = "lpo_split")
  list(splits = split_objs,
       id = names0(length(split_objs), "Resample"))
}

#' @export
print.lpo_cv <- function(x, ...) {
  cat("#", pretty(x), "\n")
  class(x) <- class(x)[!(class(x) %in% c("lpo_cv", "rset"))]
  print(x)
}


#' @exportMethod pretty.lpo_cv
#' @export pretty.lpo_cv
#' @export
#' @method pretty lpo_cv
#' @rdname pretty.vfold_cv
pretty.lpo_cv  <- function(x, ...) {
  details <- attributes(x)
  paste0("Leave-", details$p, "-out cross-validation")
}

#' @export
complement.lpo_split <- complement.vfold_split
```

**Comment by jrnold** [comment]
Definitely, it shouldn't be too hard. The whole point of a lower-level package would be to have functions that just take number of items as inputs and returns the indexes of samples. This would have a few benefits:

-  conceptually, most of these resampling algorithms don't require data frames. So it seems weird to tie implementations to data frames unless there is a big computational benefit
-  it would allow the lower level library to be used for resampling things other than data frames
-  it could allow for optimizations of these methods independent of the interface through rsample

In the meantime, I'll make PRs for any additional methods in resamplr that aren't in rsample, using the existing approach to rsample code.

Then I'll think about how to use a lower-level package when I have it more stabilized. The main thing I'm thinking about is the best object to represent sample indexes.

**Comment by topepo** [comment]
Sounds great! 

I'll probably do a release in the next few weeks so I've made a [`resamplr` branch](https://github.com/tidymodels/rsample/tree/resamplr) that you can commit to. 

I'll close this but re-open or message me if anything comes up.

**Comment by statsccpr** [comment]
I think this comment by @jrnold is exactly the functionality i'm recently looking for that rsample doesn't have

It sounds like jrnolds proposals allow a user to supply a custom boostrap procedure to be used modularly with the meta rsample heuristics

user_specialized_bootstrap(ids_parent,args){return(ids_child}

rsample(user_specialized_bootstrap,...)

i think this functionality will allow for other related requests like
https://github.com/tidymodels/rsample/issues/32
https://github.com/tidymodels/rsample/issues/75
