### ISSUE TITLE
Expand documentation for different `balance` methods for grouped sampling

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/rsample#347]
Hi @mikemahoney218,

There seems to be limited explanation anywhere (AFAIK) about how the different balancing methods work for grouped sampling. Even in `make_groups()`, the docs sort of describes how `balance = 'prop'` works, but I'm left unsure exactly what balancing by `'groups'` or `'observations'` means in this context. 

I could maybe make an educated guess, but I think some expanded documentation in `make_groups()` would be a welcome addition and improve clarity.

**Comment by mikemahoney218** [comment]
Yeah, makes total sense. I'll add something to `?group_vfold_cv()` and the vignette I'm working on for #274 . Thanks for flagging this!
