### ISSUE TITLE
Deprecate `validation_split()`

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/rsample#350]
This is a fairly confusing name because it doesn't produce a _split_ object like `initial_split()` does. It produces a single resample object. Maybe it should be named `validation_set()`, or simply `validation()`.

I think we could provide an alias for it with a better name and immediately deprecate the old name with `lifecycle::deprecate_warn()` (still works, but users get a warning once every session).

**Comment by mikemahoney218** [comment]
My only concern is that between the 1.0.0 release, TMwR publication, and workshops, it might be a bad time to deprecate one of the "main" functions from the package. But other than that I agree `validation_set()` is a better name.

**Comment by hfrick** [comment]
We have new functions to create and work with a validation split, following the mental model of a three-way split, rather than a sequence of two binary splits. The function to give you an `rset` is called `validation_set()` and we've decided to deprecate `validation_split()`, starting with the soft-deprecation level.

``` r
library(rsample)
data(ames, package = "modeldata")

# the initial split is the 3-way split
first_split <- initial_validation_split(ames)

# get rset for tuning from the 3-way split
rset_for_tuning <- validation_set(first_split)

# access to individual subsets from the initial split
ames_train <- training(first_split)
ames_val <- validation(first_split)
ames_test <- testing(first_split)

# access to individual subsets from the rset
ames_analysis <- analysis(rset_for_tuning$splits[[1]]) # same as training(first_split)
ames_assesment <- assessment(rset_for_tuning$splits[[1]]) # same as validation(first_split)
```

<sup>Created on 2023-04-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hfrick** [comment]
Additional documentation to check and update, if necessary

- [ ] vignettes
- [ ] tidymodels.org

TMwR can stay as is for now.

`extratests` should be updated now, if `validation_split()` is used in other packages (tune?) we'll update the packages as we go
