### ISSUE TITLE
Expose "constructors" for rsample & rset objects

### ISSUE THREAD

**Issue by ClaytonJY** [tidymodels/rsample#40]
Lately I've been making splits and rsets in some non-standard ways for internal (work) packages. I've been getting along fine using `new_rset`/`make_splits`/`rsplit`, but there's always a little discomfort in depending on triple-colon hidden functions in another package.

Maybe this is already on the roadmap, but I would greatly appreciate exported functions for making custom objects from this package. I suspect you'll want to wait until you've solidified the API some more, but hopefully by making a note of it here you might consider `@export`-ing `new_rset`/`make_splits` when the time is right. Thanks!

**Comment by dougmet** [comment]
I've been using `caret2rsample` to achieve this without triple colons. Seeing as `trainControl` just returns a list, so long as you have the right bits it seems to work.

I make a list called `indices`, which has two named lists: `in_indices` is a list which corresponds to `index` in `trainControl`. `out_indices` corresponds to `indexOut`. The names are the names of each resample.

```r
indices_to_rsample <- function(indices, data, method = "cv", repeats = NA,
                               number = 10) {

  # in_indices and out_indices must be named with the same names
  ctrl <- list(index = indices$in_indices,
               indexOut = indices$out_indices,
               method = method,
               repeats = repeats,
               number = number)

  rsample::caret2rsample(ctrl, data)

}
```

Now this relies on the `caret2rsample` interface remaining constant so I'm hoping for a better way soon but it at least stops CMD check from crying.
