### ISSUE TITLE
Survival Analysis Example graphs are blank

### ISSUE THREAD

**Issue by exsell-jc** [tidymodels/rsample#408]
https://rsample.tidymodels.org/articles/Applications/Survival_Analysis.html

https://rsample.tidymodels.org/articles/Applications/Survival_Analysis_files/figure-html/post-1.png

https://rsample.tidymodels.org/articles/Applications/Survival_Analysis_files/figure-html/diff-post-1.png

**Comment by hfrick** [comment]
Thanks for the issue @exsell-jc ! That article was removed in v1.0.0 of rsample (your link shows v0.1.1). It might resurface in the censored package and we're tracking that here: https://github.com/tidymodels/censored/issues/196
