### ISSUE TITLE
rsample::complement equivalent for analysis set 

### ISSUE THREAD

**Issue by sametsoekel** [tidymodels/rsample#409]
Hi,

`cv` is an rset object and I can get the assesment indices via ;

```
aka <- cv[1,] %>% select(splits) %>% pull %>% .[[1]]

indices <- rsample::complement(aka)
```

but `complement` returns `assesment` indices for that split, how can we apply it for `analysis` indices (in `complement()`'s way, without collecting `training()` and other functions )  ?

**Comment by EmilHvitfeldt** [comment]
There doesn't appear to function to do that natively right now. It might be a good idea to have. In the meantime, you can use 
`reverse_splits()` in combination with `complement()` to get your required result

``` r
library(rsample)
library(dplyr)

cv <- vfold_cv(mtcars)

aka <- cv[1,] %>% select(splits) %>% pull %>% .[[1]]

complement(aka)
#> [1]  9 12 24 26

reverse_splits(aka) %>%
  complement()
#>  [1]  1  2  3  4  5  6  7  8 10 11 13 14 15 16 17 18 19 20 21 22 23 25 27 28 29
#> [26] 30 31 32
```
