### ISSUE TITLE
train-valid-test for sliding window

### ISSUE THREAD

**Issue by Shafi2016** [tidymodels/rsample#430]
Hello,

The question is how do the parameter optimization in sliding window CV. It seems to be cross-validation is used on the entire data. If no validation data is used then how finetuning is done Or we do not need validation if we are using [tune_grid()](https://tune.tidymodels.org/reference/tune_grid.html).

However, it would to nice to add feature of validation.

For cross validation usually people prefer to have it as 

1. Train: we train the model.
2. Validation: we validate and adjust model parameters.
3. Test: unseen data.

I am using the sliding as given below. I extract the different slices for training and testing data. So I get only training and testing. [sliding window.csv] (https://github.com/tidymodels/rsample/files/11305335/sliding.window.csv). Is there to get the validation data.?

```
resamples_tscv <- sliding_window(data_prepared_tbl, 
                                 lookback =48, 
                                 assess_stop = 6, step =3, skip = 3
                                 )
plan_org <- resamples_tscv %>% tk_time_series_cv_plan()

```

  
In my case,

- First training/cross-validation (CV) window is 2004-05-01 to 2006-07-01.
- First test window for generating forecasts is 2006-08-01 to 2007-01-01.
- These windows are rolled forward three months until the end of the sample to create more windows.
The Questions is What procedure is being used in each  training window before refitting the model.

**Comment by hfrick** [comment]
Hi! :wave:

Thanks for including a definition of terms in your issue. In rsample, we use the following terminology:

- Training data is the data used to build your model, broadly defined (more on that in a second)/
- Test data is unseen data for the final performance assessment.

When we do cross-validation, we generate several pairs of data set, one for fitting the model, one for evaluating it. To distinguish that from the train/test split above, we call them analysis and assessment set respectively.

The idea with rsample is that you use `initial_split()` (or one of its variants) for the split in train/test and then pass only the training set to a function like `sliding_window()` to generate resamples (aka the pairs of analysis and assessment sets) of the training data to use for cross-validation etc.

In your case, you'd use `initial_time_split()` to preserve the ordering in the data. As an example:

``` r
library(rsample)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
data(Chicago, package = "modeldata")

range(Chicago$date)
#> [1] "2001-01-22" "2016-08-28"

# split into train and test
chicago_split <- initial_time_split(Chicago)
chicago_train <- training(chicago_split)
chicago_test <- testing(chicago_split)

range(chicago_train$date)
#> [1] "2001-01-22" "2012-10-03"
range(chicago_test$date)
#> [1] "2012-10-04" "2016-08-28"

# split training data into analysis and assessment
chicago_folds <- sliding_window(chicago_train, lookback = 365, assess_stop = 14)

get_rsplit(chicago_folds, 1) |> analysis() |> pull(date) |> range()
#> [1] "2001-01-22" "2002-01-22"
get_rsplit(chicago_folds, 1) |> assessment() |> pull(date) |> range()
#> [1] "2002-01-23" "2002-02-05"

get_rsplit(chicago_folds, 2) |> analysis() |> pull(date) |> range()
#> [1] "2001-01-23" "2002-01-23"
get_rsplit(chicago_folds, 2) |> assessment() |> pull(date) |> range()
#> [1] "2002-01-24" "2002-02-06"
```

<sup>Created on 2023-04-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Shafi2016** [comment]
Thank you for the excellent example and clarifications.
