### ISSUE TITLE
Mark `rolling_origin()` as superseded

### ISSUE THREAD

**Issue by hfrick** [tidymodels/rsample#448]
in favor of `sliding_window()`, `sliding_index()` and `sliding_period()`

**Comment by hfrick** [comment]
also remove it from the "Common Patterns" vignette?

**Comment by mikemahoney218** [comment]
Is there a way to replicate the growing analysis set with the `sliding_*` functions? I get a lot of use out of `rolling_origin` with `cumulative = TRUE`.

**Comment by hfrick** [comment]
Setting `lookback = Inf` should give you an expanding window - is that what you want?

**Comment by mikemahoney218** [comment]
Yes, that should do it! 

I'm wondering if there's a way to make that argument a bit more obvious in the documentation; I see that it's documented on the help page, but I guess I skipped over it (even when working on the package!). "Rolling origin" is the term I see used everywhere to refer to this type of CV (for instance, in all of Hyndman's writing https://otexts.com/fpp3/tscv.html ), while I haven't seen "sliding window" anywhere outside of rsample, so perhaps emphasizing in the details section that these functions can be used for rolling origin CV could be useful?

**Comment by hfrick** [comment]
Thanks, I'll try to incorporate that! Maybe highlighting it in the examples section will also help here.
