### ISSUE TITLE
`make_strata()` changes order of original factor levels

### ISSUE THREAD

**Issue by MasterLuke84** [tidymodels/rsample#450]
Hi rsample-Team, 

`make_strata()` changes the level order in factor variables in special cases, which is also commented in `line 104`.

I do not consider it as a bug in the first place, but wouldn't it be more consistent, if the level order of a factor would be preserved? 

Of course, the results are still correct and the resamplings created by eg  `vfold_cv()` (interally use of `make_strata()`) as well, but the fold indices are assigned to the (unnamed) splits based on the level order. 

Hence, if you create a strata vector out of a numerical vector by your own and pass this as a stratum in eg `vfold_cv()`, the resulting resamples are not the same (compared to just pass the name of numerical variable to `vfold_cv` directly) due do different index assignment. I know it is a very special and probably rare case...

Reprex:

``` r
set.seed(1234)
lvls <- c("[0,1)", "(1,10]")

# create original factor 
orig <- sample(lvls, size = 10, replace = TRUE) |> factor(levels = lvls)
# make strata for a factor
new <- rsample::make_strata(orig)

# different order of levels due to standard sorting
identical(levels(orig), levels(new))
#> [1] FALSE

# ---> "(" < "]"


levels(orig)
#> [1] "[0,1)"  "(1,10]"
levels(new)
#> [1] "(1,10]" "[0,1)"
```

<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

https://github.com/tidymodels/rsample/blob/1fc7cf208630b85d9afb303d0ce910c973b2bcc2/R/make_strata.R#L88-L107

**Comment by hfrick** [comment]
Hi @MasterLuke84, could you elaborate a bit more on why that would be a problem? I agree that this isn't perfect but I currently don't see why it would be important.
