### ISSUE TITLE
Use cli errors

### ISSUE THREAD

**Issue by hfrick** [tidymodels/rsample#457]
Most or all errors thrown in this package are made via `rlang::abort()`. We are transitioning to `cli::cli_abort()` to make use of the richer styling options for errors via cli (which calls rlang under the hood). 

It is often sufficient to search for and replace the rlang version with the cli version together with adding a little bit of styling.

Some examples of the styling possibilities are in the [general introduction](https://cli.r-lib.org/articles/semantic-cli.html) under the section of [Inline text formatting](https://cli.r-lib.org/articles/semantic-cli.html#inline-text-formatting). More details on [inline formatting](https://cli.r-lib.org/reference/inline-markup.html) and [pluralization](https://cli.r-lib.org/articles/pluralization.html). 

One aspect to watch out for when transitioning from `rlang::abort()` to `cli::cli_abort()` are messages pre-assembled from user input as described [here](https://rlang.r-lib.org/dev/reference/topic-condition-formatting.html#transitioning-from-abort-to-cli-abort-).

#499 can serve as an example.

We are splitting this up into several batches:
- [x] #504
- [x] #505
- [x] #506
- [x] #507
- [x] #508
- [x] #509
- [x] #510
- [x] #511
- [x] #512
- [x] #513
- [x] #514

**Comment by hfrick** [comment]
Closing this after all the tidy dev day PRs! Thank you @PriKalra @Dpananos and @JamesHWade!! 🙌

**Comment by PriKalra** [comment]
Thank you @hfrick for the patience and the opportunity! I will come back to support again!
