### ISSUE TITLE
assessment and analysis functions on objects other than rsplit

### ISSUE THREAD

**Issue by EdwinTh** [tidymodels/rsample#46]
I had great trouble fixing a bug recently, both `assessment` and `analysis` returned the analysis set. The reason appeared to be that my `rsplit` element was still in a list. See the following minimal example.

```r
library(tidyverse)
library(rsample)
mtcars_spl <- mtcars %>% vfold_cv()
mtcars_spl$splits[1] %>% assessment()
mtcars_spl$splits[1] %>% analysis()
```

This is because `as.data.frame` is called by both functions. Wouldn't it be better if they only work on `rsplit` objects and throw an informative error when called on other objects?

**Comment by topepo** [comment]
Point taken!
