### ISSUE TITLE
Support for oversampling and undersampling

### ISSUE THREAD

**Issue by jxu** [tidymodels/rsample#460]
https://www.tidymodels.org/learn/models/sub-sampling/ from this guide I can use `themis::step_rose()` in a recipe to oversample. 
Is this functionality that can be implemented in rsample? `strata` in `initial_sample` almost does this.

**Comment by EmilHvitfeldt** [comment]
the support for oversampling and understand is already facilitated with the {themis} package. Is there a specific use-case you have that can't be solved with {rsample} + {themis}?

**Comment by jxu** [comment]
Not in particular, I was just curious why this is not in rsample.
