### ISSUE TITLE
Importing `recipes` introduces many implicit dependencies

### ISSUE THREAD

**Issue by echasnovski** [tidymodels/rsample#48]
At current moment, installation of `rsample` (supposing `tidyverse` is installed) causes many packages to be installed as dependencies of `recipes`. I had 20 extra packages installed (excluding `recipes` itself):
<details>
<summary>List of extra packages</summary>
‘numDeriv’, ‘SQUAREM’, ‘abind’, ‘lava’, ‘kernlab’, ‘CVST’, ‘DEoptimR’, ‘magic’, ‘prodlim’, ‘DRR’, ‘robustbase’, ‘sfsmisc’, ‘geometry’, ‘ipred’, ‘dimRed’, ‘timeDate’, ‘ddalpha’, ‘gower’, ‘RcppRoll’, ‘pls’
</details>
<br>

I understand the reason to facilitate using the `recipes` with `rsample` by providing `prepper()` wrapper, but I think 20 packages not explicitly needed for core functionality is a little bit too much for one simple wrapper. Maybe it is a good idea to move `recipes` back to `Suggests`, mention it with wrapper in vignette, and possibly add `rsample` into `recipes` `Import` (as it already has many imported packages)? Keep `rsample` more light-weight?

Also current situation might be inconvenient for package authors willing to import `rsample`.

**Comment by topepo** [comment]
It would make sense to move `prepper` to `recipes` (which would import `rsample`). I'll work on that.

**Comment by ClaytonJY** [comment]
@topepo would it also make sense to move `form_pred` to `recipes`? Seems a bit out-of-place here and doesn't seem to be used internally at all.

**Comment by topepo** [comment]
I'm going to leave that one in `rsample`. You don't really need it for `recipes` and it is just a little function to help with training materials.
