### ISSUE TITLE
inner_split(): S3 method to retrive splitting arguments

### ISSUE THREAD

**Issue by topepo** [tidymodels/rsample#491]
It's a bit tedious to do this: 

``` r
library(tidymodels)

set.seed(19)
ad_v_fold <- vfold_cv(ad_data, v = 5, strata = Class)
ad_v_fold_attr <- attributes(ad_v_fold)[ c("v", "repeats", "strata", "breaks", "pool")]

v_fold_inner <- inner_split(ad_v_fold$splits[[1]], ad_v_fold_attr)
```

<sup>Created on 2024-05-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

IIRC you have an internal function to do this?

**Comment by simonpcouch** [comment]
https://github.com/tidymodels/rsample/blob/7d35a8eb0b53ca2561818cd60bdd756badd0ac2e/R/misc.R#L298-L312

**Comment by hfrick** [comment]
Closing this as the helper exist :) 

@topepo it's currently exported but that might change. If you find usage for it that suggests it should stay exported please comment on https://github.com/tidymodels/rsample/pull/495 🙌
