### ISSUE TITLE
inner_split(): no initial_split() arguments

### ISSUE THREAD

**Issue by topepo** [tidymodels/rsample#492]
It looks like we don't retain anything (probably because this is an rsplit and not an rset)(validation splits came later)

``` r
library(tidymodels)

set.seed(11)
ad_split <- initial_split(ad_data, prop = 3/4, strata = Class)

# We should keep the prop and strata arguments
names(attributes(ad_split))
#> [1] "names" "class"

# We do here:
ad_vl_split <- initial_validation_split(ad_data, strata = Class)
names(attributes(ad_vl_split)$val_att)
#> [1] "prop"   "strata" "breaks" "pool"
```

<sup>Created on 2024-05-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

That said, maybe we should in this specific case.

**Comment by hfrick** [comment]
From the discussion with @simonpcouch in https://github.com/tidymodels/rsample/pull/489#discussion_r1613651288: yes, let's keep that info so we can use in the context of `last_fit()`!
