### ISSUE TITLE
Easier flattening via unnest.rset method

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/rsample#51]
In some cases working with a list column of tibbles is overkill. For example:

```r
 bootstraps(mtcars) %>% 
   mutate(train = map(splits, assessment)) %>%
   unnest(train) %>% 
   group_by(id) %>% 
   summarize(mean = mean(mpg))
```

I propose adding an `rset` method for `unnest()` so that only a single line is need to flatten an `rset`:

```r
unnest.rset <- function (data, dataset = c("assessment", "analysis"), ...) {
  mutate(train = map(splits, get(dataset))) %>%
    unnest(train) %>% 
    group_by(id)
}
```

or an `unnest_by()` once that comes to `dplyr`.

**Comment by kmdupr33** [comment]
I started looking into this. Now that `unnest` requires specifying columns, it seems like this proposal is less useful. It seems like the usage and implementation would have to look like this:

```r
unnest.rset <- function (data, dataset = c("assessment", "analysis"), ...) {
  data %>%
    mutate(train = map(splits, get(dataset))) %>%
    as_tibble() %>%
    tidyr::unnest(...) %>%
    group_by(id)
}

 bootstraps(mtcars) %>% 
   unnest(cols = c(train)) %>% 
   summarize(mean = mean(mpg))
```

I find the fact that the `unnest.rset` function adds a column that you need to reference when calling it is confusing, but I'm open to idea that others may not agree. I can move forward with this if we think its fine. :)

**Comment by juliasilge** [comment]
Hmmmm, that is a really good point. Needing to pass in a column that a user did not create would be a pretty big barrier, and doesn't really us much beyond what already exists. Let us get back to you on this.

``` r
library(tidymodels)

bootstraps(mtcars) %>% 
  mutate(train = map(splits, assessment)) %>%
  unnest(train)
#> # A tibble: 286 x 13
#>    splits id      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear
#>    <list> <chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1 <spli… Boot…  21       6 160     110  3.9   2.62  16.5     0     1     4
#>  2 <spli… Boot…  21       6 160     110  3.9   2.88  17.0     0     1     4
#>  3 <spli… Boot…  18.7     8 360     175  3.15  3.44  17.0     0     0     3
#>  4 <spli… Boot…  14.3     8 360     245  3.21  3.57  15.8     0     0     3
#>  5 <spli… Boot…  24.4     4 147.     62  3.69  3.19  20       1     0     4
#>  6 <spli… Boot…  17.8     6 168.    123  3.92  3.44  18.9     1     0     4
#>  7 <spli… Boot…  16.4     8 276.    180  3.07  4.07  17.4     0     0     3
#>  8 <spli… Boot…  15.2     8 276.    180  3.07  3.78  18       0     0     3
#>  9 <spli… Boot…  33.9     4  71.1    65  4.22  1.84  19.9     1     1     4
#> 10 <spli… Boot…  21.5     4 120.     97  3.7   2.46  20.0     1     0     3
#> # … with 276 more rows, and 1 more variable: carb <dbl>
```

<sup>Created on 2020-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Side note:** I am not convinced that the output of such a method should be grouped.

**Comment by kmdupr33** [comment]
> **Side note:** I am not convinced that the output of such a method should be grouped.

Happy to hear that. I feel the same way. I was just following the example. 😌

**Comment by alexpghayes** [comment]
My thinking on this has changed as well. In essence I see two workflows for resampling/cv/bootstrapping. The first workflow involves recreating an `rset` and then iterating over the `rsplit` objects by hand. This is the "default" tidymodels / many-models approach. The second workflow is more like `strapgod`, where you essential pass a function that you want to e.g. bootstrap, and the low level interface abstracts the details away (cc @gvwilson re: your tidyblocks interface question).

Anyway, unnesting the `rsplits` puts you in a middle ground I really don't like -- you have observations but also they are nested within folds but the folds have been flattened. The unit of computation is nebulous. This is in contrast to the workflows I described above, where the data is very clearly either a `rsplit`, or a single data frame. If I were to re-write the code in my example today I would choose to go all in on `rsplits` or a `strapgod` type approach and would avoid this pattern.

**Comment by topepo** [comment]
Yes. TBH I wasn't really on-board. I think that `strapgod` fills the need for simple and efficient bootstrapping. Also, many of the `tidyr` verbs are not meant to be extended I think (I learned that the hard way).
