### ISSUE TITLE
rolling_origin() should allow for an expanding window + sliding window in the same call

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/rsample#56]
This Uber post talks about how useful it can be to expand a window up until you have enough data, and then proceed to use a sliding window. I think that could be useful and I don't think rolling_origin() does this at the moment. https://eng.uber.com/forecasting-introduction/

**Comment by topepo** [comment]
Looking at their figure 4, I think that the `cumulative` options does this:
```r
rof <- rolling_origin(mtcars[1:20, ], initial = 10, assess = 2, cumulative = TRUE)
rof <- tidy(rof) %>%
  mutate(Row = factor(Row, levels = paste(1:20)))

ggplot(rof, aes(x = Resample, y = Row, fill = Data)) + 
  geom_tile(alpha = .5) + scale_fill_brewer(palette = "Set1") + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) + 
  xlab("") + ylab("Training Set Sample") + 
  theme(legend.position = "top") + 
  coord_flip()
```

![image](https://user-images.githubusercontent.com/5731043/45254520-a5c4fb00-b347-11e8-9a11-9b0c2baae031.png)

**Comment by topepo** [comment]
So something like:

```r

trim_analysis <- function(x, max_tr = Inf) {
  x$in_id <- tail(x$in_id, max_tr)
  x
}
rof <- rolling_origin(mtcars[1:20, ], initial = 10, assess = 2, cumulative = TRUE)
rof$splits <- map(rof$splits, trim_analysis, 14)
rof <- tidy(rof) %>%
  mutate(Row = factor(Row, levels = paste(1:20)))

ggplot(rof, aes(x = Resample, y = Row, fill = Data)) + 
  geom_tile(alpha = .5) + scale_fill_brewer(palette = "Set1") + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) + 
  xlab("") + ylab("Training Set Sample") + 
  theme(legend.position = "top") + 
  coord_flip()
```

![image](https://user-images.githubusercontent.com/5731043/45255395-c98e3e00-b353-11e8-829c-7e4acb616a64.png)

**Comment by DavisVaughan** [comment]
Yes that graph looks correct!

**Comment by topepo** [comment]
We we can put in an new option (`max_n`?) and default it to `Inf`. 

Is there anything that we would do differently to do the additional filtering on a time basis (like `tsibble`) versus an index-based basis? So something like "at most three years of data in the analysis set"?

**Comment by DavisVaughan** [comment]
Two things:

1) Does `max_n` have a real meaning for `cumulative = FALSE`? It's a fixed window size the entire time. So it would either do nothing, or truncate whatever `initial` was set to.

2) I've often thought that `rolling_origin()` is really 2 functions in 1. I'm interested in how tied you are to that function as opposed to breaking them out into the (imho more meaningfully named) functions of `sliding_window()` and `expanding_window()`. It would remove the need for `cumulative`, and if we decide that `max_n` isn't meaningful for the `cumulative=FALSE` case then `sliding_window()` just wouldn't get that argument.

> additional filtering on a time basis

I need to think about this a bit more. We might would need to make a generic that can do something different for a `tsibble` object.

**Comment by ClaytonJY** [comment]
@DavisVaughan would that split hide the similarity in concept when doing a hybrid like `expanding_window(tbl, max_n = 10)`, since you could say it _becomes_ a sliding window once the max is hit? I definitely like those names more than `rolling_origin`, though.

I think you're right that `max_n` wouldn't make sense if `cumulative = FALSE` (should be ignored then), but if you note that in the docs and maybe throw a warning, is that so bad?

(having tsibble methods could be pretty awesome, esp. if you could use `lubridate` periods to have e.g. `assess = days(3)`)

**Comment by DavisVaughan** [comment]
> would that split hide the similarity in concept when doing a hybrid 

It would, but I was okay with this as you can either think of it as capping the expanding window or becoming a sliding window. We can document the nuances.

> if you note that in the docs and maybe throw a warning, is that so bad?

I don't think this would be the worst thing in the world. I mainly thought that splitting out the two functions made sense because of the clearer naming, and this `max_n` case is just the first time something has come up as a more concrete argument for why they should be separated.

> having tsibble methods could be pretty awesome

I agree that some sort of time based slicing and dicing would be pretty great. It will take some thinking to define exactly what is allowed though. As one weird example, what if I am on `2018-01-30` and I want to assess `months(1)` forward worth of data? `as.Date("2018-01-30") + months(1) = NA` so that's not going to be useful as a boundary.

**Comment by ClaytonJY** [comment]
yeah, the more intuitive naming is a big bonus to your pair of functions, that alone makes me lean that way. It's really not my place to say how this should go, but I think either is great and look forward to the enhanced functionality.

---

Good catch on the NA result; forgot that happens. Could use `%m+%` or `add_with_rollback()`, though the latter gets messy quick, like do you expose the extra args? Using `%m+%` gives `2018-02-28`, which I _think_ is what I'd expect, but it's certainly debatable.
