### ISSUE TITLE
Problems with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [tidymodels/rsample#74]
I'm in the process of preparing the release for _tibble_ 2.0.0. The _rsample_ package imports or suggests _tibble_.

I'm seeing errors when testing your package with the dev version of _tibble_. The errors seem to come from a more accurate handling of attributes in `[.tbl_df()`. https://github.com/krlmlr/rsample/commit/1cf13ab7eee676cb7e204e199e9cf0e479be2ffa fixes the issue, but I'm not sure if this is correct.

Could you please install the development version of _tibble_ and run the tests in your package, so that we get a better understanding of the problem?

See https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/ for details on the upcoming release.

**Comment by topepo** [comment]
Will do. I think something similar has to happen for `recipes`. I'll work on it tomorrow.

**Comment by krlmlr** [comment]
_recipes_ no longer shows failures in my checks, but I muted many warnings.

**Comment by krlmlr** [comment]
I'm adding a compat mode for _recipes_.

**Comment by topepo** [comment]
Thanks!
