### ISSUE TITLE
Alternative bootstrap schemes

### ISSUE THREAD

**Issue by asbates** [tidymodels/rsample#75]
Would it be possible to have support for alternatives to the standard bootstrap? I'm thinking of two cases specifically. In *subsampling* we draw samples of size b < n without replacement. In the *m-out-of-n bootstrap*, samples of size m < n are drawn with replacement. Both methods are more general; they are valid in situations where the standard bootstrap isn't.

I would love to help if you think this is worth implementing.

**Comment by topepo** [comment]
I want to keep subsampling in a different place. `recipes` does down-sampling and we'll probably have another package of recipe steps for other methods too. 

I view subsampling to be part of pre-processing and that's more appropriate for `recipes`. 

For example, we'd want the analysis set to be sampled and _not_ the assessment set. `recipes` is set up to [do that](https://tidymodels.github.io/recipes/articles/articles/Subsampling.html). 

You're welcome to suggest different schemes there too.
