### ISSUE TITLE
Time for a cheatsheet?

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/rsample#78]
Possibly combine with `recipes` and a brief list-column example? Then I'd imagine maybe a second cheatsheet for `parsnip` and `dials`, etc, a little down the line?

**Comment by fbchow** [comment]
The list column workflow diagrams from the 2nd page of the [purr cheatsheet](https://purrr.tidyverse.org/#cheatsheet) can be repurposed to represent the `rset` to `recipe` workflow. 

Maybe add a short [block](https://speakerdeck.com/statsfan/rsample-sampler?slide=18) on what the `rsplit` object looks like.

**Comment by juliasilge** [comment]
We've focused more on [tidymodels.org](https://www.tidymodels.org/) and other "whole analysis" styles of documentation so I'm going to close this for now, since it's not on our near term priorities.
