### ISSUE TITLE
Question: How to do up- and downsampling?

### ISSUE THREAD

**Issue by denismaciel** [tidymodels/rsample#87]
* Are there equivalent's to caret's `upSample` and `downSample`?
* What's the rsample way of achieving this?

**Comment by topepo** [comment]
We leave that to `recipes`. There is documentation for [up](https://tidymodels.github.io/recipes/reference/step_upsample.html)- and [down](https://tidymodels.github.io/recipes/reference/step_downsample.html)-sampling there.
