### ISSUE TITLE
Confidence intervals and the high/low-level interface split

### ISSUE THREAD

**Issue by alexpghayes** [tidymodels/rsample#88]
I know that fancier point estimates for model performance in the vein of .632, .632+, etc, etc are on the way thanks to @fbchow. Based on some recent pain with the `boot` package, it would also be nice to add some convenience functions to calculate various types of more efficient bootstrapped confidence intervals (which I now realized is what @malcolmbarrett asked about at rstudio::conf).

I haven't seen the .632 interface yet, but:
- does it easily extend to confidence intervals?
- what is the overall strategy for differentiating between low level infrastructure like `rsets`, etc, and high level convenience functions that work more in the vein of the `boot` package?
  - Where does, say, `bootstrapify()` fit in?

**Comment by topepo** [comment]
I think that the current thinking is that `rsample` would have more traditional `purrr::map`-type interfaces that operate on statistics that are in columns while @DavisVaughan's [`strapgod`](https://github.com/DavisVaughan/strapgod) would do more "on-the-fly" computations that do not (by default) save the constituent statistics. 

(It's been a while so hopefully I've summarized this well)
