### ISSUE TITLE
Functionality for multiple splits as part/extension of initial_split()?

### ISSUE THREAD

**Issue by exuberantleigh** [tidymodels/rsample#89]
Would be lovely to be able to do more than one initial split. 

We regularly do at least two splits these days where we're having to use an additional initial_split() on the test dataset. Which means carrying two rsplit objects through our workflow and duplicating some of the data, aka it ain't pretty. I'd like to be able to maintain the same structure from start to finish of workflow regardless of the number of splits needed. 

I've got a workaround for my team's purposes, but thought this issue might be of more general interest. And indeed, just saw a closed issue with this same suggestion( #85 ), though not sure why it was closed. 

Plus, I'm pretty sure there's this guy who teaches these predictive modeling workshops where he suggests splitting your data in all sorts of ways, if ya have the data to spend. 

Thoughts @topepo @DavisVaughan ?

**Comment by topepo** [comment]
`rsample` is (unfortunately) about binary splits. We can get around this but we'd have to rewrite the backend for this function (but keep the same api). 

In the meantime, you could use `modelr::resample_partition()`: 

``` r
library(purrr)
library(modelr)

iris %>% 
  resample_partition(c(test = 0.3, train = 0.6, val = .1)) %>% 
  map_int(nrow)
#>  test train   val 
#>    44    90    16
```

Created on 2019-04-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by exuberantleigh** [comment]
Gotcha! Thanks for the response.
