### ISSUE TITLE
Is this package spark friendly?

### ISSUE THREAD

**Issue by alexhallam** [tidymodels/rsample#90]
I am guessing that there is no easy way to use rsample in SparkR or sparklyr, but I thought I would ask.

I use `rolling_origin` and `initial_time_split` a lot on smaller samples of my data. I would like to have the option to extend this functionality in databricks on spark for a larger data set.

**Comment by topepo** [comment]
No, not really. spark operates in an entirely different way that `rsample` (which relies on R data frames in memory). I'd put an issue into `sparklyr` to see if they have any tools.
