### ISSUE TITLE
specify multiple strata in initial_split

### ISSUE THREAD

**Issue by macek2** [tidymodels/rsample#94]
### Minimal, reproducible example:

It would be really great to be able to split out your dataset by multiple strata, for example:

```r
initial_split(mtcars, strata = c('cyl', 'vs'))
```

#### _Minimal_ Reproducible Dataset:

```r
mtcars
```

#### Minimal, runnable code:

```r
library(rsample)

# Set the seed before using random numbers
set.seed(4121)

# Works
initial_split(mtcars, strata = c('cyl'))
# Does not work, but would be great if it did,
# initial_split(mtcars, strata = c('cyl', 'vs'))

```

**Comment by topepo** [comment]
I've experimented with this quite a bit and there's really no good way to do that (above and beyond you making a strata variable via `mutate`. For example, both of the variables in your example are numeric and the stratification would happen in a way that you might not have intended. 

In most cases (and examples that people have sent me), there are a lot of sparse or empty cells in the strata so it would be hard to automate this in a general way.

**Comment by macek2** [comment]
Thanks for the feedback.
