### ISSUE TITLE
skip = n in rolling_origin() actually skips n+1 values

### ISSUE THREAD

**Issue by statist-bhfz** [tidymodels/rsample#97]
Here is an example of this unexpected behaviour

```
> res <- tibble(id = LETTERS[1:8],
+        val = 1:8) %>%
+   rolling_origin(initial = 3, assess = 2, skip = 2, cumulative = FALSE)
> 
> training(res$splits[[1]])
# A tibble: 3 x 2
  id      val
  <chr> <int>
1 A         1
2 B         2
3 C         3
> testing(res$splits[[1]])
# A tibble: 2 x 2
  id      val
  <chr> <int>
1 D         4
2 E         5
> training(res$splits[[2]])
# A tibble: 3 x 2
  id      val
  <chr> <int>
1 D         4
2 E         5
3 F         6
> testing(res$splits[[2]])
# A tibble: 2 x 2
  id      val
  <chr> <int>
1 G         7
2 H         8
```

**Comment by topepo** [comment]
This is consistent with [the documentation](https://tidymodels.github.io/rsample/reference/rolling_origin.html): 

> When `skip = 0`, the resampling data sets will increment by one position. Suppose that the rows of a data set are consecutive days. Using `skip = 6` will make the analysis data set operate on weeks instead of days. The assessment set size is not affected by this option.

The idea is that, if you left a value of zero, you are not skipping over any additional samples. "skip" here implies moving above and beyond the basic "move one position" scheme.

**Comment by statist-bhfz** [comment]
@topepo thanks, I get it.
Please add this illustrative example to documentation and maybe to https://tidymodels.github.io/rsample/articles/Applications/Time_Series.html. I'm not the only one who have some problems with this point: author of https://www.business-science.io/timeseries-analysis/2018/04/18/keras-lstm-sunspots-time-series-prediction.html also do it wrong, whereas in more recent version of this publication (https://blogs.rstudio.com/tensorflow/posts/2018-06-25-sunspots-lstm/) correction was made.
